import { SeedUniversity } from "./types";

export const AMERICAS_UNIVERSITIES: SeedUniversity[] = [
  // =========================================================================
  // UNITED STATES (US)
  // =========================================================================
  {
    seedKey: "seed-us-harvard",
    name: "Harvard University",
    shortName: "Harvard",
    country: "United States",
    countryCode: "US",
    city: "Cambridge",
    state: "Massachusetts",
    website: "https://www.harvard.edu",
    domain: "harvard.edu",
    timezone: "America/New_York",
    isVerified: true,
    campuses: [
      { name: "Cambridge Main Campus", city: "Cambridge", isMain: true },
      { name: "Allston Campus (Engineering)", city: "Boston", isMain: false },
      { name: "Longwood Campus (Medical)", city: "Boston", isMain: false },
    ],
    departments: [
      { name: "Harvard John A. Paulson School of Engineering and Applied Sciences (SEAS)", faculty: "Engineering & Applied Sciences" },
      { name: "Department of Computer Science", faculty: "SEAS" },
      { name: "Harvard Business School (HBS)", faculty: "Business" },
      { name: "Department of Economics", faculty: "Faculty of Arts and Sciences" },
    ],
  },
  {
    seedKey: "seed-us-mit",
    name: "Massachusetts Institute of Technology",
    shortName: "MIT",
    country: "United States",
    countryCode: "US",
    city: "Cambridge",
    state: "Massachusetts",
    website: "https://www.mit.edu",
    domain: "mit.edu",
    timezone: "America/New_York",
    isVerified: true,
    campuses: [{ name: "Cambridge Main Campus", city: "Cambridge", isMain: true }],
    departments: [
      { name: "Department of Electrical Engineering and Computer Science (EECS)", faculty: "MIT Schwarzman College of Computing" },
      { name: "MIT Sloan School of Management", faculty: "Management" },
      { name: "Department of Mechanical Engineering", faculty: "School of Engineering" },
    ],
  },
  {
    seedKey: "seed-us-stanford",
    name: "Stanford University",
    shortName: "Stanford",
    country: "United States",
    countryCode: "US",
    city: "Stanford",
    state: "California",
    website: "https://www.stanford.edu",
    domain: "stanford.edu",
    timezone: "America/Los_Angeles",
    isVerified: true,
    campuses: [{ name: "Stanford Main Campus", city: "Stanford", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "School of Engineering" },
      { name: "Department of Electrical Engineering", faculty: "School of Engineering" },
      { name: "Stanford Graduate School of Business (GSB)", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-us-berkeley",
    name: "University of California, Berkeley",
    shortName: "UC Berkeley",
    country: "United States",
    countryCode: "US",
    city: "Berkeley",
    state: "California",
    website: "https://www.berkeley.edu",
    domain: "berkeley.edu",
    timezone: "America/Los_Angeles",
    isVerified: true,
    campuses: [{ name: "Berkeley Main Campus", city: "Berkeley", isMain: true }],
    departments: [
      { name: "Department of Electrical Engineering and Computer Sciences (EECS)", faculty: "College of Computing, Data Science, and Society" },
      { name: "Haas School of Business", faculty: "Business" },
      { name: "Department of Economics", faculty: "Letters & Science" },
    ],
  },
  {
    seedKey: "seed-us-princeton",
    name: "Princeton University",
    shortName: "Princeton",
    country: "United States",
    countryCode: "US",
    city: "Princeton",
    state: "New Jersey",
    website: "https://www.princeton.edu",
    domain: "princeton.edu",
    timezone: "America/New_York",
    isVerified: true,
    campuses: [{ name: "Princeton Main Campus", city: "Princeton", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "School of Engineering and Applied Science" },
      { name: "Department of Operations Research and Financial Engineering (ORFE)", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-us-columbia",
    name: "Columbia University in the City of New York",
    shortName: "Columbia",
    country: "United States",
    countryCode: "US",
    city: "New York",
    state: "New York",
    website: "https://www.columbia.edu",
    domain: "columbia.edu",
    timezone: "America/New_York",
    isVerified: true,
    campuses: [
      { name: "Morningside Heights Main Campus", city: "New York", isMain: true },
      { name: "Manhattanville Campus", city: "New York", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Fu Foundation School of Engineering and Applied Science" },
      { name: "Columbia Business School", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-us-yale",
    name: "Yale University",
    shortName: "Yale",
    country: "United States",
    countryCode: "US",
    city: "New Haven",
    state: "Connecticut",
    website: "https://www.yale.edu",
    domain: "yale.edu",
    timezone: "America/New_York",
    isVerified: true,
    campuses: [{ name: "New Haven Main Campus", city: "New Haven", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Faculty of Arts and Sciences" },
      { name: "Yale School of Management", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-us-caltech",
    name: "California Institute of Technology",
    shortName: "Caltech",
    country: "United States",
    countryCode: "US",
    city: "Pasadena",
    state: "California",
    website: "https://www.caltech.edu",
    domain: "caltech.edu",
    timezone: "America/Los_Angeles",
    isVerified: true,
    campuses: [{ name: "Pasadena Main Campus", city: "Pasadena", isMain: true }],
    departments: [
      { name: "Computing and Mathematical Sciences (CMS)", faculty: "Division of Engineering and Applied Science" },
      { name: "Division of Physics, Mathematics and Astronomy", faculty: "Sciences" },
    ],
  },
  {
    seedKey: "seed-us-uchicago",
    name: "The University of Chicago",
    shortName: "UChicago",
    country: "United States",
    countryCode: "US",
    city: "Chicago",
    state: "Illinois",
    website: "https://www.uchicago.edu",
    domain: "uchicago.edu",
    timezone: "America/Chicago",
    isVerified: true,
    campuses: [{ name: "Hyde Park Main Campus", city: "Chicago", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Physical Sciences Division" },
      { name: "Booth School of Business", faculty: "Business" },
      { name: "Kenneth C. Griffin Department of Economics", faculty: "Social Sciences" },
    ],
  },
  {
    seedKey: "seed-us-penn",
    name: "University of Pennsylvania",
    shortName: "Penn / UPenn",
    country: "United States",
    countryCode: "US",
    city: "Philadelphia",
    state: "Pennsylvania",
    website: "https://www.upenn.edu",
    domain: "upenn.edu",
    timezone: "America/New_York",
    isVerified: true,
    campuses: [{ name: "University City Main Campus", city: "Philadelphia", isMain: true }],
    departments: [
      { name: "Department of Computer and Information Science (CIS)", faculty: "Penn Engineering" },
      { name: "The Wharton School", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-us-cornell",
    name: "Cornell University",
    shortName: "Cornell",
    country: "United States",
    countryCode: "US",
    city: "Ithaca",
    state: "New York",
    website: "https://www.cornell.edu",
    domain: "cornell.edu",
    timezone: "America/New_York",
    isVerified: true,
    campuses: [
      { name: "Ithaca Main Campus", city: "Ithaca", isMain: true },
      { name: "Cornell Tech Campus (Roosevelt Island)", city: "New York", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Cornell Ann S. Bowers College of Computing and Information Science" },
      { name: "SC Johnson College of Business", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-us-cmu",
    name: "Carnegie Mellon University",
    shortName: "CMU",
    country: "United States",
    countryCode: "US",
    city: "Pittsburgh",
    state: "Pennsylvania",
    website: "https://www.cmu.edu",
    domain: "cmu.edu",
    timezone: "America/New_York",
    isVerified: true,
    campuses: [
      { name: "Pittsburgh Main Campus", city: "Pittsburgh", isMain: true },
      { name: "Silicon Valley Campus", city: "Mountain View", isMain: false },
    ],
    departments: [
      { name: "Computer Science Department (CSD)", faculty: "School of Computer Science" },
      { name: "Human-Computer Interaction Institute (HCII)", faculty: "School of Computer Science" },
      { name: "Language Technologies Institute (LTI)", faculty: "School of Computer Science" },
      { name: "Tepper School of Business", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-us-ucla",
    name: "University of California, Los Angeles",
    shortName: "UCLA",
    country: "United States",
    countryCode: "US",
    city: "Los Angeles",
    state: "California",
    website: "https://www.ucla.edu",
    domain: "ucla.edu",
    timezone: "America/Los_Angeles",
    isVerified: true,
    campuses: [{ name: "Westwood Main Campus", city: "Los Angeles", isMain: true }],
    departments: [
      { name: "Computer Science Department", faculty: "Samueli School of Engineering" },
      { name: "Anderson School of Management", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-us-umich",
    name: "University of Michigan",
    shortName: "UMich",
    country: "United States",
    countryCode: "US",
    city: "Ann Arbor",
    state: "Michigan",
    website: "https://umich.edu",
    domain: "umich.edu",
    timezone: "America/Detroit",
    isVerified: true,
    campuses: [
      { name: "Ann Arbor Main Campus", city: "Ann Arbor", isMain: true },
      { name: "Dearborn Campus", city: "Dearborn", isMain: false },
    ],
    departments: [
      { name: "Computer Science and Engineering Division (CSE)", faculty: "College of Engineering" },
      { name: "Stephen M. Ross School of Business", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-us-uw",
    name: "University of Washington",
    shortName: "UW / U-Dub",
    country: "United States",
    countryCode: "US",
    city: "Seattle",
    state: "Washington",
    website: "https://www.washington.edu",
    domain: "washington.edu",
    timezone: "America/Los_Angeles",
    isVerified: true,
    campuses: [
      { name: "Seattle Main Campus", city: "Seattle", isMain: true },
      { name: "Bothell Campus", city: "Bothell", isMain: false },
      { name: "Tacoma Campus", city: "Tacoma", isMain: false },
    ],
    departments: [
      { name: "Paul G. Allen School of Computer Science & Engineering", faculty: "College of Engineering" },
      { name: "Foster School of Business", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-us-utaustin",
    name: "The University of Texas at Austin",
    shortName: "UT Austin",
    country: "United States",
    countryCode: "US",
    city: "Austin",
    state: "Texas",
    website: "https://www.utexas.edu",
    domain: "utexas.edu",
    timezone: "America/Chicago",
    isVerified: true,
    campuses: [{ name: "Austin Main Campus", city: "Austin", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "College of Natural Sciences" },
      { name: "McCombs School of Business", faculty: "Business" },
      { name: "Cockrell School of Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-us-gatech",
    name: "Georgia Institute of Technology",
    shortName: "Georgia Tech",
    country: "United States",
    countryCode: "US",
    city: "Atlanta",
    state: "Georgia",
    website: "https://www.gatech.edu",
    domain: "gatech.edu",
    timezone: "America/New_York",
    isVerified: true,
    campuses: [
      { name: "Atlanta Main Campus", city: "Atlanta", isMain: true },
      { name: "Lorraine Campus (Metz)", city: "Metz", isMain: false },
    ],
    departments: [
      { name: "College of Computing", faculty: "Computing" },
      { name: "School of Electrical and Computer Engineering", faculty: "College of Engineering" },
      { name: "Scheller College of Business", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-us-uiuc",
    name: "University of Illinois Urbana-Champaign",
    shortName: "UIUC",
    country: "United States",
    countryCode: "US",
    city: "Urbana",
    state: "Illinois",
    website: "https://illinois.edu",
    domain: "illinois.edu",
    timezone: "America/Chicago",
    isVerified: true,
    campuses: [{ name: "Urbana-Champaign Main Campus", city: "Urbana", isMain: true }],
    departments: [
      { name: "Thomas M. Siebel Center for Computer Science", faculty: "The Grainger College of Engineering" },
      { name: "Gies College of Business", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-us-purdue",
    name: "Purdue University",
    shortName: "Purdue",
    country: "United States",
    countryCode: "US",
    city: "West Lafayette",
    state: "Indiana",
    website: "https://www.purdue.edu",
    domain: "purdue.edu",
    timezone: "America/Indiana/Indianapolis",
    isVerified: true,
    campuses: [{ name: "West Lafayette Main Campus", city: "West Lafayette", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "College of Science" },
      { name: "Elmore Family School of Electrical and Computer Engineering", faculty: "College of Engineering" },
    ],
  },
  {
    seedKey: "seed-us-nyu",
    name: "New York University",
    shortName: "NYU",
    country: "United States",
    countryCode: "US",
    city: "New York",
    state: "New York",
    website: "https://www.nyu.edu",
    domain: "nyu.edu",
    timezone: "America/New_York",
    isVerified: true,
    campuses: [
      { name: "Washington Square Main Campus", city: "New York", isMain: true },
      { name: "Brooklyn Campus (Tandon School of Engineering)", city: "Brooklyn", isMain: false },
    ],
    departments: [
      { name: "Courant Institute of Mathematical Sciences (Computer Science)", faculty: "Arts and Science" },
      { name: "Tandon School of Engineering - Computer Science & Engineering", faculty: "Engineering" },
      { name: "Stern School of Business", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-us-northwestern",
    name: "Northwestern University",
    shortName: "Northwestern",
    country: "United States",
    countryCode: "US",
    city: "Evanston",
    state: "Illinois",
    website: "https://www.northwestern.edu",
    domain: "northwestern.edu",
    timezone: "America/Chicago",
    isVerified: true,
    campuses: [
      { name: "Evanston Main Campus", city: "Evanston", isMain: true },
      { name: "Chicago Campus (Medical/Law)", city: "Chicago", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "McCormick School of Engineering" },
      { name: "Kellogg School of Management", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-us-ucsd",
    name: "University of California, San Diego",
    shortName: "UC San Diego",
    country: "United States",
    countryCode: "US",
    city: "La Jolla",
    state: "California",
    website: "https://ucsd.edu",
    domain: "ucsd.edu",
    timezone: "America/Los_Angeles",
    isVerified: true,
    campuses: [{ name: "La Jolla Main Campus", city: "La Jolla", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering (CSE)", faculty: "Jacobs School of Engineering" },
      { name: "Halıcıoğlu Data Science Institute (HDSI)", faculty: "Data Science" },
    ],
  },
  {
    seedKey: "seed-us-duke",
    name: "Duke University",
    shortName: "Duke",
    country: "United States",
    countryCode: "US",
    city: "Durham",
    state: "North Carolina",
    website: "https://duke.edu",
    domain: "duke.edu",
    timezone: "America/New_York",
    isVerified: true,
    campuses: [{ name: "Durham Main Campus", city: "Durham", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Trinity College of Arts & Sciences" },
      { name: "Pratt School of Engineering", faculty: "Engineering" },
      { name: "Fuqua School of Business", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-us-jhu",
    name: "Johns Hopkins University",
    shortName: "JHU",
    country: "United States",
    countryCode: "US",
    city: "Baltimore",
    state: "Maryland",
    website: "https://www.jhu.edu",
    domain: "jhu.edu",
    timezone: "America/New_York",
    isVerified: true,
    campuses: [
      { name: "Homewood Main Campus", city: "Baltimore", isMain: true },
      { name: "East Baltimore Campus (Medical)", city: "Baltimore", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Whiting School of Engineering" },
      { name: "School of Medicine", faculty: "Medicine" },
    ],
  },
  {
    seedKey: "seed-us-wisc",
    name: "University of Wisconsin–Madison",
    shortName: "UW–Madison",
    country: "United States",
    countryCode: "US",
    city: "Madison",
    state: "Wisconsin",
    website: "https://www.wisc.edu",
    domain: "wisc.edu",
    timezone: "America/Chicago",
    isVerified: true,
    campuses: [{ name: "Madison Main Campus", city: "Madison", isMain: true }],
    departments: [
      { name: "Department of Computer Sciences", faculty: "School of Computer, Data & Information Sciences (CDIS)" },
      { name: "Wisconsin School of Business", faculty: "Business" },
    ],
  },

  // =========================================================================
  // CANADA (CA)
  // =========================================================================
  {
    seedKey: "seed-ca-toronto",
    name: "University of Toronto",
    shortName: "U of T",
    country: "Canada",
    countryCode: "CA",
    city: "Toronto",
    state: "Ontario",
    website: "https://www.utoronto.ca",
    domain: "utoronto.ca",
    timezone: "America/Toronto",
    isVerified: true,
    campuses: [
      { name: "St. George Main Campus (Downtown)", city: "Toronto", isMain: true },
      { name: "Mississauga Campus (UTM)", city: "Mississauga", isMain: false },
      { name: "Scarborough Campus (UTSC)", city: "Scarborough", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Faculty of Arts and Science" },
      { name: "Edward S. Rogers Sr. Department of Electrical & Computer Engineering", faculty: "Faculty of Applied Science and Engineering" },
      { name: "Rotman School of Management", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-ca-ubc",
    name: "The University of British Columbia",
    shortName: "UBC",
    country: "Canada",
    countryCode: "CA",
    city: "Vancouver",
    state: "British Columbia",
    website: "https://www.ubc.ca",
    domain: "ubc.ca",
    timezone: "America/Vancouver",
    isVerified: true,
    campuses: [
      { name: "Vancouver Main Campus (Point Grey)", city: "Vancouver", isMain: true },
      { name: "Okanagan Campus", city: "Kelowna", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Faculty of Science" },
      { name: "Department of Electrical and Computer Engineering", faculty: "Faculty of Applied Science" },
      { name: "UBC Sauder School of Business", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-ca-waterloo",
    name: "University of Waterloo",
    shortName: "UWaterloo",
    country: "Canada",
    countryCode: "CA",
    city: "Waterloo",
    state: "Ontario",
    website: "https://uwaterloo.ca",
    domain: "uwaterloo.ca",
    timezone: "America/Toronto",
    isVerified: true,
    campuses: [{ name: "Waterloo Main Campus", city: "Waterloo", isMain: true }],
    departments: [
      { name: "David R. Cheriton School of Computer Science", faculty: "Faculty of Mathematics" },
      { name: "Department of Electrical and Computer Engineering", faculty: "Faculty of Engineering" },
    ],
  },
  {
    seedKey: "seed-ca-mcgill",
    name: "McGill University",
    shortName: "McGill",
    country: "Canada",
    countryCode: "CA",
    city: "Montreal",
    state: "Quebec",
    website: "https://www.mcgill.ca",
    domain: "mcgill.ca",
    timezone: "America/Toronto",
    isVerified: true,
    campuses: [
      { name: "Downtown Main Campus", city: "Montreal", isMain: true },
      { name: "Macdonald Campus", city: "Sainte-Anne-de-Bellevue", isMain: false },
    ],
    departments: [
      { name: "School of Computer Science", faculty: "Faculty of Science" },
      { name: "Desautels Faculty of Management", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-ca-alberta",
    name: "University of Alberta",
    shortName: "UAlberta",
    country: "Canada",
    countryCode: "CA",
    city: "Edmonton",
    state: "Alberta",
    website: "https://www.ualberta.ca",
    domain: "ualberta.ca",
    timezone: "America/Edmonton",
    isVerified: true,
    campuses: [{ name: "North Campus", city: "Edmonton", isMain: true }],
    departments: [
      { name: "Department of Computing Science", faculty: "Faculty of Science" },
      { name: "Alberta School of Business", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-ca-mcmaster",
    name: "McMaster University",
    shortName: "McMaster",
    country: "Canada",
    countryCode: "CA",
    city: "Hamilton",
    state: "Ontario",
    website: "https://www.mcmaster.ca",
    domain: "mcmaster.ca",
    timezone: "America/Toronto",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Hamilton", isMain: true }],
    departments: [
      { name: "Department of Computing and Software", faculty: "Faculty of Engineering" },
      { name: "DeGroote School of Business", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-ca-montreal",
    name: "Université de Montréal",
    shortName: "UdeM",
    country: "Canada",
    countryCode: "CA",
    city: "Montreal",
    state: "Quebec",
    website: "https://www.umontreal.ca",
    domain: "umontreal.ca",
    timezone: "America/Toronto",
    isVerified: true,
    campuses: [{ name: "Mount Royal Main Campus", city: "Montreal", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Operations Research (DIRO)", faculty: "Faculty of Arts and Sciences" },
      { name: "Mila – Quebec AI Institute", faculty: "Artificial Intelligence" },
    ],
  },
  {
    seedKey: "seed-ca-western",
    name: "Western University",
    shortName: "Western",
    country: "Canada",
    countryCode: "CA",
    city: "London",
    state: "Ontario",
    website: "https://www.uwo.ca",
    domain: "uwo.ca",
    timezone: "America/Toronto",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "London", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Faculty of Science" },
      { name: "Ivey Business School", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-ca-queens",
    name: "Queen's University at Kingston",
    shortName: "Queen's",
    country: "Canada",
    countryCode: "CA",
    city: "Kingston",
    state: "Ontario",
    website: "https://www.queensu.ca",
    domain: "queensu.ca",
    timezone: "America/Toronto",
    isVerified: true,
    campuses: [{ name: "Kingston Main Campus", city: "Kingston", isMain: true }],
    departments: [
      { name: "School of Computing", faculty: "Faculty of Arts and Science" },
      { name: "Smith School of Business", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-ca-calgary",
    name: "University of Calgary",
    shortName: "UCalgary",
    country: "Canada",
    countryCode: "CA",
    city: "Calgary",
    state: "Alberta",
    website: "https://www.ucalgary.ca",
    domain: "ucalgary.ca",
    timezone: "America/Edmonton",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Calgary", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Faculty of Science" },
      { name: "Haskayne School of Business", faculty: "Business" },
    ],
  },

  // =========================================================================
  // MEXICO (MX)
  // =========================================================================
  {
    seedKey: "seed-mx-unam",
    name: "Universidad Nacional Autónoma de México",
    shortName: "UNAM",
    country: "Mexico",
    countryCode: "MX",
    city: "Mexico City",
    state: "CDMX",
    website: "https://www.unam.mx",
    domain: "unam.mx",
    timezone: "America/Mexico_City",
    isVerified: true,
    campuses: [{ name: "Ciudad Universitaria Main Campus (Coyoacán)", city: "Mexico City", isMain: true }],
    departments: [
      { name: "Institute of Applied Mathematics and Systems (IIMAS) - Computer Science", faculty: "Sciences" },
      { name: "Faculty of Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-mx-itesm",
    name: "Tecnológico de Monterrey",
    shortName: "Tec de Monterrey",
    country: "Mexico",
    countryCode: "MX",
    city: "Monterrey",
    state: "Nuevo León",
    website: "https://tec.mx",
    domain: "tec.mx",
    timezone: "America/Monterrey",
    isVerified: true,
    campuses: [
      { name: "Campus Monterrey", city: "Monterrey", isMain: true },
      { name: "Campus Ciudad de México", city: "Mexico City", isMain: false },
      { name: "Campus Guadalajara", city: "Guadalajara", isMain: false },
    ],
    departments: [
      { name: "School of Engineering and Sciences - Computing and Information Technologies", faculty: "Engineering" },
      { name: "EGADE Business School", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-mx-ipn",
    name: "Instituto Politécnico Nacional",
    shortName: "IPN",
    country: "Mexico",
    countryCode: "MX",
    city: "Mexico City",
    state: "CDMX",
    website: "https://www.ipn.mx",
    domain: "ipn.mx",
    timezone: "America/Mexico_City",
    isVerified: true,
    campuses: [{ name: "Zacatenco Main Campus", city: "Mexico City", isMain: true }],
    departments: [
      { name: "School of Computing (ESCOM)", faculty: "Engineering & Physical-Mathematical Sciences" },
      { name: "Center for Computing Research (CIC)", faculty: "Computing" },
    ],
  },

  // =========================================================================
  // BRAZIL (BR)
  // =========================================================================
  {
    seedKey: "seed-br-usp",
    name: "Universidade de São Paulo",
    shortName: "USP",
    country: "Brazil",
    countryCode: "BR",
    city: "São Paulo",
    state: "São Paulo",
    website: "https://www.usp.br",
    domain: "usp.br",
    timezone: "America/Sao_Paulo",
    isVerified: true,
    campuses: [
      { name: "Cidade Universitária Main Campus", city: "São Paulo", isMain: true },
      { name: "São Carlos Campus", city: "São Carlos", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science (IME-USP)", faculty: "Institute of Mathematics and Statistics" },
      { name: "Polytechnic School of the University of São Paulo (Poli-USP)", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-br-unicamp",
    name: "Universidade Estadual de Campinas",
    shortName: "UNICAMP",
    country: "Brazil",
    countryCode: "BR",
    city: "Campinas",
    state: "São Paulo",
    website: "https://www.unicamp.br",
    domain: "unicamp.br",
    timezone: "America/Sao_Paulo",
    isVerified: true,
    campuses: [{ name: "Barão Geraldo Main Campus", city: "Campinas", isMain: true }],
    departments: [
      { name: "Institute of Computing (IC)", faculty: "Computing" },
      { name: "School of Electrical and Computer Engineering (FEEC)", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-br-ufrj",
    name: "Universidade Federal do Rio de Janeiro",
    shortName: "UFRJ",
    country: "Brazil",
    countryCode: "BR",
    city: "Rio de Janeiro",
    state: "Rio de Janeiro",
    website: "https://ufrj.br",
    domain: "ufrj.br",
    timezone: "America/Sao_Paulo",
    isVerified: true,
    campuses: [{ name: "Cidade Universitária (Fundão)", city: "Rio de Janeiro", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Institute of Mathematics" },
      { name: "COPPE - Graduate School of Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-br-unesp",
    name: "Universidade Estadual Paulista",
    shortName: "UNESP",
    country: "Brazil",
    countryCode: "BR",
    city: "São Paulo",
    state: "São Paulo",
    website: "https://www2.unesp.br",
    domain: "unesp.br",
    timezone: "America/Sao_Paulo",
    isVerified: true,
    campuses: [{ name: "Bauru Campus", city: "Bauru", isMain: true }],
    departments: [
      { name: "Department of Computing", faculty: "Faculty of Sciences" },
      { name: "Faculty of Engineering", faculty: "Engineering" },
    ],
  },

  // =========================================================================
  // ARGENTINA, CHILE & COLOMBIA (AR, CL, CO)
  // =========================================================================
  {
    seedKey: "seed-ar-uba",
    name: "Universidad de Buenos Aires",
    shortName: "UBA",
    country: "Argentina",
    countryCode: "AR",
    city: "Buenos Aires",
    website: "https://www.uba.ar",
    domain: "uba.ar",
    timezone: "America/Argentina/Buenos_Aires",
    isVerified: true,
    campuses: [{ name: "Ciudad Universitaria", city: "Buenos Aires", isMain: true }],
    departments: [
      { name: "Departamento de Computación", faculty: "Facultad de Ciencias Exactas y Naturales" },
      { name: "Facultad de Ingeniería", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-ar-unlp",
    name: "Universidad Nacional de La Plata",
    shortName: "UNLP",
    country: "Argentina",
    countryCode: "AR",
    city: "La Plata",
    state: "Buenos Aires Province",
    website: "https://unlp.edu.ar",
    domain: "unlp.edu.ar",
    timezone: "America/Argentina/Buenos_Aires",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "La Plata", isMain: true }],
    departments: [
      { name: "Facultad de Informática", faculty: "Informatics" },
      { name: "Facultad de Ingeniería", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-cl-uc",
    name: "Pontificia Universidad Católica de Chile",
    shortName: "UC Chile",
    country: "Chile",
    countryCode: "CL",
    city: "Santiago",
    state: "Santiago Metropolitan Region",
    website: "https://www.uc.cl",
    domain: "uc.cl",
    timezone: "America/Santiago",
    isVerified: true,
    campuses: [{ name: "Campus San Joaquín", city: "Santiago", isMain: true }],
    departments: [
      { name: "Departamento de Ciencia de la Computación (DCC)", faculty: "Escuela de Ingeniería" },
      { name: "Escuela de Administración", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-cl-uchile",
    name: "Universidad de Chile",
    shortName: "UChile",
    country: "Chile",
    countryCode: "CL",
    city: "Santiago",
    state: "Santiago Metropolitan Region",
    website: "https://uchile.cl",
    domain: "uchile.cl",
    timezone: "America/Santiago",
    isVerified: true,
    campuses: [{ name: "Beauchef Campus (FCFM)", city: "Santiago", isMain: true }],
    departments: [
      { name: "Departamento de Ciencias de la Computación (DCC)", faculty: "Facultad de Ciencias Físicas y Matemáticas" },
      { name: "Facultad de Economía y Negocios", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-co-uniandes",
    name: "Universidad de los Andes",
    shortName: "UniAndes",
    country: "Colombia",
    countryCode: "CO",
    city: "Bogotá",
    state: "Bogotá D.C.",
    website: "https://uniandes.edu.co",
    domain: "uniandes.edu.co",
    timezone: "America/Bogota",
    isVerified: true,
    campuses: [{ name: "Bogotá Main Campus", city: "Bogotá", isMain: true }],
    departments: [
      { name: "Departamento de Ingeniería de Sistemas y Computación (DISC)", faculty: "Facultad de Ingeniería" },
      { name: "Facultad de Administración", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-co-unal",
    name: "Universidad Nacional de Colombia",
    shortName: "UNAL",
    country: "Colombia",
    countryCode: "CO",
    city: "Bogotá",
    state: "Bogotá D.C.",
    website: "https://unal.edu.co",
    domain: "unal.edu.co",
    timezone: "America/Bogota",
    isVerified: true,
    campuses: [
      { name: "Sede Bogotá Main Campus", city: "Bogotá", isMain: true },
      { name: "Sede Medellín", city: "Medellín", isMain: false },
    ],
    departments: [
      { name: "Departamento de Ingeniería de Sistemas e Industrial", faculty: "Facultad de Ingeniería" },
      { name: "Facultad de Ciencias", faculty: "Sciences" },
    ],
  },
];
