import { SeedUniversity } from "./types";

export const EAST_SOUTHEAST_ASIA_UNIVERSITIES: SeedUniversity[] = [
  // =========================================================================
  // SINGAPORE (SG)
  // =========================================================================
  {
    seedKey: "seed-sg-nus",
    name: "National University of Singapore",
    shortName: "NUS",
    country: "Singapore",
    countryCode: "SG",
    city: "Singapore",
    website: "https://nus.edu.sg",
    domain: "nus.edu.sg",
    timezone: "Asia/Singapore",
    isVerified: true,
    campuses: [
      { name: "Kent Ridge Main Campus", city: "Singapore", isMain: true },
      { name: "Bukit Timah Campus", city: "Singapore", isMain: false },
      { name: "Outram Campus", city: "Singapore", isMain: false },
    ],
    departments: [
      { name: "School of Computing", faculty: "Computing" },
      { name: "Faculty of Engineering", faculty: "Engineering" },
      { name: "NUS Business School", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-sg-ntu",
    name: "Nanyang Technological University",
    shortName: "NTU Singapore",
    country: "Singapore",
    countryCode: "SG",
    city: "Singapore",
    website: "https://ntu.edu.sg",
    domain: "ntu.edu.sg",
    timezone: "Asia/Singapore",
    isVerified: true,
    campuses: [{ name: "Yunnan Garden Main Campus", city: "Singapore", isMain: true }],
    departments: [
      { name: "College of Computing and Data Science", faculty: "Computing" },
      { name: "College of Engineering", faculty: "Engineering" },
      { name: "Nanyang Business School", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-sg-smu",
    name: "Singapore Management University",
    shortName: "SMU",
    country: "Singapore",
    countryCode: "SG",
    city: "Singapore",
    website: "https://smu.edu.sg",
    domain: "smu.edu.sg",
    timezone: "Asia/Singapore",
    isVerified: true,
    campuses: [{ name: "City Campus (Bras Basah)", city: "Singapore", isMain: true }],
    departments: [
      { name: "School of Computing and Information Systems (SCIS)", faculty: "Computing" },
      { name: "Lee Kong Chian School of Business", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-sg-sutd",
    name: "Singapore University of Technology and Design",
    shortName: "SUTD",
    country: "Singapore",
    countryCode: "SG",
    city: "Singapore",
    website: "https://sutd.edu.sg",
    domain: "sutd.edu.sg",
    timezone: "Asia/Singapore",
    isVerified: true,
    campuses: [{ name: "Somapah Main Campus", city: "Singapore", isMain: true }],
    departments: [
      { name: "Information Systems Technology and Design (ISTD)", faculty: "Information Technology" },
      { name: "Engineering Product Development (EPD)", faculty: "Engineering" },
    ],
  },

  // =========================================================================
  // MALAYSIA (MY)
  // =========================================================================
  {
    seedKey: "seed-my-um",
    name: "Universiti Malaya",
    shortName: "UM",
    country: "Malaysia",
    countryCode: "MY",
    city: "Kuala Lumpur",
    state: "Federal Territory of Kuala Lumpur",
    website: "https://um.edu.my",
    domain: "um.edu.my",
    timezone: "Asia/Kuala_Lumpur",
    isVerified: true,
    campuses: [{ name: "Kuala Lumpur Main Campus", city: "Kuala Lumpur", isMain: true }],
    departments: [
      { name: "Faculty of Computer Science and Information Technology", faculty: "Computing" },
      { name: "Faculty of Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-my-upm",
    name: "Universiti Putra Malaysia",
    shortName: "UPM",
    country: "Malaysia",
    countryCode: "MY",
    city: "Serdang",
    state: "Selangor",
    website: "https://upm.edu.my",
    domain: "upm.edu.my",
    timezone: "Asia/Kuala_Lumpur",
    isVerified: true,
    campuses: [{ name: "Serdang Main Campus", city: "Serdang", isMain: true }],
    departments: [
      { name: "Faculty of Computer Science and Information Technology", faculty: "Computing" },
      { name: "Faculty of Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-my-ukm",
    name: "Universiti Kebangsaan Malaysia",
    shortName: "UKM",
    country: "Malaysia",
    countryCode: "MY",
    city: "Bangi",
    state: "Selangor",
    website: "https://ukm.edu.my",
    domain: "ukm.edu.my",
    timezone: "Asia/Kuala_Lumpur",
    isVerified: true,
    campuses: [{ name: "Bangi Main Campus", city: "Bangi", isMain: true }],
    departments: [
      { name: "Faculty of Information Science and Technology", faculty: "Computing" },
      { name: "Faculty of Engineering and Built Environment", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-my-usm",
    name: "Universiti Sains Malaysia",
    shortName: "USM",
    country: "Malaysia",
    countryCode: "MY",
    city: "George Town",
    state: "Penang",
    website: "https://usm.my",
    domain: "usm.my",
    timezone: "Asia/Kuala_Lumpur",
    isVerified: true,
    campuses: [
      { name: "Main Campus (Penang)", city: "George Town", isMain: true },
      { name: "Engineering Campus (Nibong Tebal)", city: "Nibong Tebal", isMain: false },
    ],
    departments: [
      { name: "School of Computer Sciences", faculty: "Computing" },
      { name: "School of Electrical & Electronic Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-my-utm",
    name: "Universiti Teknologi Malaysia",
    shortName: "UTM",
    country: "Malaysia",
    countryCode: "MY",
    city: "Skudai",
    state: "Johor",
    website: "https://utm.my",
    domain: "utm.my",
    timezone: "Asia/Kuala_Lumpur",
    isVerified: true,
    campuses: [
      { name: "Johor Bahru Main Campus", city: "Skudai", isMain: true },
      { name: "Kuala Lumpur Campus", city: "Kuala Lumpur", isMain: false },
    ],
    departments: [
      { name: "Faculty of Computing", faculty: "Computing" },
      { name: "Faculty of Electrical Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-my-monash",
    name: "Monash University Malaysia",
    shortName: "Monash Malaysia",
    country: "Malaysia",
    countryCode: "MY",
    city: "Subang Jaya",
    state: "Selangor",
    website: "https://monash.edu.my",
    domain: "monash.edu.my",
    timezone: "Asia/Kuala_Lumpur",
    isVerified: true,
    campuses: [{ name: "Sunway City Campus", city: "Subang Jaya", isMain: true }],
    departments: [
      { name: "School of Information Technology", faculty: "Information Technology" },
      { name: "School of Engineering", faculty: "Engineering" },
    ],
  },

  // =========================================================================
  // INDONESIA (ID)
  // =========================================================================
  {
    seedKey: "seed-id-ui",
    name: "Universitas Indonesia",
    shortName: "UI",
    country: "Indonesia",
    countryCode: "ID",
    city: "Depok",
    state: "West Java",
    website: "https://ui.ac.id",
    domain: "ui.ac.id",
    timezone: "Asia/Jakarta",
    isVerified: true,
    campuses: [
      { name: "Depok Main Campus", city: "Depok", isMain: true },
      { name: "Salemba Campus", city: "Jakarta", isMain: false },
    ],
    departments: [
      { name: "Faculty of Computer Science (Fasilkom UI)", faculty: "Computer Science" },
      { name: "Faculty of Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-id-itb",
    name: "Institut Teknologi Bandung",
    shortName: "ITB",
    country: "Indonesia",
    countryCode: "ID",
    city: "Bandung",
    state: "West Java",
    website: "https://itb.ac.id",
    domain: "itb.ac.id",
    timezone: "Asia/Jakarta",
    isVerified: true,
    campuses: [{ name: "Ganesha Main Campus", city: "Bandung", isMain: true }],
    departments: [
      { name: "School of Electrical Engineering and Informatics (STEI)", faculty: "Engineering & Informatics" },
      { name: "Faculty of Industrial Technology", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-id-ugm",
    name: "Universitas Gadjah Mada",
    shortName: "UGM",
    country: "Indonesia",
    countryCode: "ID",
    city: "Yogyakarta",
    state: "Special Region of Yogyakarta",
    website: "https://ugm.ac.id",
    domain: "ugm.ac.id",
    timezone: "Asia/Jakarta",
    isVerified: true,
    campuses: [{ name: "Bulaksumur Main Campus", city: "Yogyakarta", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Electronics", faculty: "Mathematics and Natural Sciences" },
      { name: "Faculty of Engineering", faculty: "Engineering" },
    ],
  },

  // =========================================================================
  // THAILAND (TH)
  // =========================================================================
  {
    seedKey: "seed-th-chula",
    name: "Chulalongkorn University",
    shortName: "Chula",
    country: "Thailand",
    countryCode: "TH",
    city: "Bangkok",
    website: "https://chula.ac.th",
    domain: "chula.ac.th",
    timezone: "Asia/Bangkok",
    isVerified: true,
    campuses: [{ name: "Pathum Wan Main Campus", city: "Bangkok", isMain: true }],
    departments: [
      { name: "Department of Computer Engineering", faculty: "Faculty of Engineering" },
      { name: "Chulalongkorn Business School", faculty: "Commerce & Accountancy" },
    ],
  },
  {
    seedKey: "seed-th-mahidol",
    name: "Mahidol University",
    shortName: "MU Thailand",
    country: "Thailand",
    countryCode: "TH",
    city: "Salaya",
    state: "Nakhon Pathom",
    website: "https://mahidol.ac.th",
    domain: "mahidol.ac.th",
    timezone: "Asia/Bangkok",
    isVerified: true,
    campuses: [{ name: "Salaya Main Campus", city: "Salaya", isMain: true }],
    departments: [
      { name: "Faculty of Information and Communication Technology (ICT)", faculty: "ICT" },
      { name: "Faculty of Medicine Siriraj Hospital", faculty: "Medicine" },
    ],
  },

  // =========================================================================
  // PHILIPPINES & VIETNAM (PH, VN)
  // =========================================================================
  {
    seedKey: "seed-ph-up",
    name: "University of the Philippines Diliman",
    shortName: "UPD",
    country: "Philippines",
    countryCode: "PH",
    city: "Quezon City",
    state: "Metro Manila",
    website: "https://upd.edu.ph",
    domain: "upd.edu.ph",
    timezone: "Asia/Manila",
    isVerified: true,
    campuses: [{ name: "Diliman Main Campus", city: "Quezon City", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "College of Engineering" },
      { name: "Electrical and Electronics Engineering Institute (EEEI)", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-ph-admu",
    name: "Ateneo de Manila University",
    shortName: "ADMU",
    country: "Philippines",
    countryCode: "PH",
    city: "Quezon City",
    state: "Metro Manila",
    website: "https://ateneo.edu",
    domain: "ateneo.edu",
    timezone: "Asia/Manila",
    isVerified: true,
    campuses: [{ name: "Loyola Heights Main Campus", city: "Quezon City", isMain: true }],
    departments: [
      { name: "Department of Information Systems and Computer Science (DISCS)", faculty: "Science and Engineering" },
      { name: "John Gokongwei School of Management", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-vn-vnu-hcm",
    name: "Vietnam National University, Ho Chi Minh City",
    shortName: "VNU-HCM",
    country: "Vietnam",
    countryCode: "VN",
    city: "Ho Chi Minh City",
    website: "https://vnuhcm.edu.vn",
    domain: "vnuhcm.edu.vn",
    timezone: "Asia/Ho_Chi_Minh",
    isVerified: true,
    campuses: [{ name: "Thu Duc Main Campus", city: "Ho Chi Minh City", isMain: true }],
    departments: [
      { name: "University of Information Technology (UIT)", faculty: "Information Technology" },
      { name: "Ho Chi Minh City University of Technology (HCMUT)", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-vn-vnu-hn",
    name: "Vietnam National University, Hanoi",
    shortName: "VNU-HN",
    country: "Vietnam",
    countryCode: "VN",
    city: "Hanoi",
    website: "https://vnu.edu.vn",
    domain: "vnu.edu.vn",
    timezone: "Asia/Ho_Chi_Minh",
    isVerified: true,
    campuses: [{ name: "Cau Giay Main Campus", city: "Hanoi", isMain: true }],
    departments: [
      { name: "University of Engineering and Technology (VNU-UET)", faculty: "Engineering" },
      { name: "VNU University of Science", faculty: "Science" },
    ],
  },

  // =========================================================================
  // JAPAN (JP)
  // =========================================================================
  {
    seedKey: "seed-jp-u-tokyo",
    name: "The University of Tokyo",
    shortName: "UTokyo",
    country: "Japan",
    countryCode: "JP",
    city: "Tokyo",
    state: "Kantō",
    website: "https://www.u-tokyo.ac.jp",
    domain: "u-tokyo.ac.jp",
    timezone: "Asia/Tokyo",
    isVerified: true,
    campuses: [
      { name: "Hongo Main Campus (Bunkyo)", city: "Tokyo", isMain: true },
      { name: "Komaba Campus (Meguro)", city: "Tokyo", isMain: false },
      { name: "Kashiwa Campus (Chiba)", city: "Kashiwa", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Graduate School of Information Science and Technology" },
      { name: "Faculty of Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-jp-kyoto",
    name: "Kyoto University",
    shortName: "Kyodai",
    country: "Japan",
    countryCode: "JP",
    city: "Kyoto",
    state: "Kansai",
    website: "https://www.kyoto-u.ac.jp",
    domain: "kyoto-u.ac.jp",
    timezone: "Asia/Tokyo",
    isVerified: true,
    campuses: [
      { name: "Yoshida Main Campus", city: "Kyoto", isMain: true },
      { name: "Uji Campus", city: "Uji", isMain: false },
      { name: "Katsura Campus", city: "Kyoto", isMain: false },
    ],
    departments: [
      { name: "Department of Intelligence Science and Technology", faculty: "Graduate School of Informatics" },
      { name: "Faculty of Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-jp-titech",
    name: "Institute of Science Tokyo (formerly Tokyo Tech)",
    shortName: "Science Tokyo",
    country: "Japan",
    countryCode: "JP",
    city: "Tokyo",
    state: "Kantō",
    website: "https://www.isct.ac.jp",
    domain: "isct.ac.jp",
    timezone: "Asia/Tokyo",
    isVerified: true,
    campuses: [{ name: "Ookayama Main Campus", city: "Tokyo", isMain: true }],
    departments: [
      { name: "School of Computing", faculty: "Computing" },
      { name: "School of Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-jp-osaka",
    name: "Osaka University",
    shortName: "Handai",
    country: "Japan",
    countryCode: "JP",
    city: "Suita",
    state: "Osaka",
    website: "https://www.osaka-u.ac.jp",
    domain: "osaka-u.ac.jp",
    timezone: "Asia/Tokyo",
    isVerified: true,
    campuses: [{ name: "Suita Main Campus", city: "Suita", isMain: true }],
    departments: [
      { name: "Graduate School of Information Science and Technology", faculty: "Information Science" },
      { name: "School of Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-jp-waseda",
    name: "Waseda University",
    shortName: "Waseda",
    country: "Japan",
    countryCode: "JP",
    city: "Tokyo",
    state: "Kantō",
    website: "https://www.waseda.jp",
    domain: "waseda.jp",
    timezone: "Asia/Tokyo",
    isVerified: true,
    campuses: [{ name: "Waseda Main Campus (Shinjuku)", city: "Tokyo", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "School of Fundamental Science and Engineering" },
      { name: "School of Commerce", faculty: "Commerce" },
    ],
  },
  {
    seedKey: "seed-jp-keio",
    name: "Keio University",
    shortName: "Keio",
    country: "Japan",
    countryCode: "JP",
    city: "Tokyo",
    state: "Kantō",
    website: "https://www.keio.ac.jp",
    domain: "keio.ac.jp",
    timezone: "Asia/Tokyo",
    isVerified: true,
    campuses: [
      { name: "Mita Main Campus", city: "Tokyo", isMain: true },
      { name: "Yagami Campus (Science & Technology)", city: "Yokohama", isMain: false },
      { name: "SFC Campus", city: "Fujisawa", isMain: false },
    ],
    departments: [
      { name: "Department of Information and Computer Science", faculty: "Faculty of Science and Technology" },
      { name: "Faculty of Economics", faculty: "Economics" },
    ],
  },

  // =========================================================================
  // SOUTH KOREA (KR)
  // =========================================================================
  {
    seedKey: "seed-kr-snu",
    name: "Seoul National University",
    shortName: "SNU",
    country: "South Korea",
    countryCode: "KR",
    city: "Seoul",
    state: "Gwanak-gu",
    website: "https://en.snu.ac.kr",
    domain: "snu.ac.kr",
    timezone: "Asia/Seoul",
    isVerified: true,
    campuses: [{ name: "Gwanak Main Campus", city: "Seoul", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "College of Engineering" },
      { name: "Department of Electrical and Computer Engineering", faculty: "College of Engineering" },
      { name: "College of Business Administration", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-kr-kaist",
    name: "KAIST - Korea Advanced Institute of Science and Technology",
    shortName: "KAIST",
    country: "South Korea",
    countryCode: "KR",
    city: "Daejeon",
    state: "Yuseong-gu",
    website: "https://www.kaist.ac.kr",
    domain: "kaist.ac.kr",
    timezone: "Asia/Seoul",
    isVerified: true,
    campuses: [
      { name: "Main Campus (Daejeon)", city: "Daejeon", isMain: true },
      { name: "Seoul Campus", city: "Seoul", isMain: false },
    ],
    departments: [
      { name: "School of Computing", faculty: "Computing" },
      { name: "School of Electrical Engineering", faculty: "Engineering" },
      { name: "Kim Jaechul Graduate School of AI", faculty: "Artificial Intelligence" },
    ],
  },
  {
    seedKey: "seed-kr-yonsei",
    name: "Yonsei University",
    shortName: "Yonsei",
    country: "South Korea",
    countryCode: "KR",
    city: "Seoul",
    state: "Seodaemun-gu",
    website: "https://www.yonsei.ac.kr",
    domain: "yonsei.ac.kr",
    timezone: "Asia/Seoul",
    isVerified: true,
    campuses: [
      { name: "Sinchon Main Campus", city: "Seoul", isMain: true },
      { name: "International Campus (Songdo)", city: "Incheon", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "College of Computing" },
      { name: "School of Business", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-kr-korea",
    name: "Korea University",
    shortName: "KU Korea",
    country: "South Korea",
    countryCode: "KR",
    city: "Seoul",
    state: "Seongbuk-gu",
    website: "https://www.korea.edu",
    domain: "korea.edu",
    timezone: "Asia/Seoul",
    isVerified: true,
    campuses: [{ name: "Anam Main Campus", city: "Seoul", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "College of Informatics" },
      { name: "Korea University Business School (KUBS)", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-kr-postech",
    name: "Pohang University of Science and Technology",
    shortName: "POSTECH",
    country: "South Korea",
    countryCode: "KR",
    city: "Pohang",
    state: "Gyeongsangbuk-do",
    website: "https://www.postech.ac.kr",
    domain: "postech.ac.kr",
    timezone: "Asia/Seoul",
    isVerified: true,
    campuses: [{ name: "Pohang Main Campus", city: "Pohang", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "Engineering" },
      { name: "Graduate School of Artificial Intelligence", faculty: "Artificial Intelligence" },
    ],
  },

  // =========================================================================
  // CHINA (CN)
  // =========================================================================
  {
    seedKey: "seed-cn-tsinghua",
    name: "Tsinghua University",
    shortName: "Tsinghua",
    country: "China",
    countryCode: "CN",
    city: "Beijing",
    state: "Haidian District",
    website: "https://www.tsinghua.edu.cn",
    domain: "tsinghua.edu.cn",
    timezone: "Asia/Shanghai",
    isVerified: true,
    campuses: [{ name: "Haidian Main Campus", city: "Beijing", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Technology", faculty: "Information Science and Technology" },
      { name: "School of Economics and Management", faculty: "Economics & Management" },
    ],
  },
  {
    seedKey: "seed-cn-pku",
    name: "Peking University",
    shortName: "PKU",
    country: "China",
    countryCode: "CN",
    city: "Beijing",
    state: "Haidian District",
    website: "https://english.pku.edu.cn",
    domain: "pku.edu.cn",
    timezone: "Asia/Shanghai",
    isVerified: true,
    campuses: [{ name: "Yanyuan Main Campus", city: "Beijing", isMain: true }],
    departments: [
      { name: "School of Computer Science", faculty: "Information Science" },
      { name: "Guanghua School of Management", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-cn-fudan",
    name: "Fudan University",
    shortName: "Fudan",
    country: "China",
    countryCode: "CN",
    city: "Shanghai",
    state: "Yangpu District",
    website: "https://www.fudan.edu.cn",
    domain: "fudan.edu.cn",
    timezone: "Asia/Shanghai",
    isVerified: true,
    campuses: [{ name: "Handan Main Campus", city: "Shanghai", isMain: true }],
    departments: [
      { name: "School of Computer Science", faculty: "Science & Technology" },
      { name: "School of Management", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-cn-sjtu",
    name: "Shanghai Jiao Tong University",
    shortName: "SJTU",
    country: "China",
    countryCode: "CN",
    city: "Shanghai",
    state: "Minhang District",
    website: "https://en.sjtu.edu.cn",
    domain: "sjtu.edu.cn",
    timezone: "Asia/Shanghai",
    isVerified: true,
    campuses: [{ name: "Minhang Main Campus", city: "Shanghai", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "School of Electronic Information and Electrical Engineering" },
      { name: "Antai College of Economics and Management", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-cn-zju",
    name: "Zhejiang University",
    shortName: "ZJU",
    country: "China",
    countryCode: "CN",
    city: "Hangzhou",
    state: "Zhejiang",
    website: "https://www.zju.edu.cn",
    domain: "zju.edu.cn",
    timezone: "Asia/Shanghai",
    isVerified: true,
    campuses: [{ name: "Zijingang Main Campus", city: "Hangzhou", isMain: true }],
    departments: [
      { name: "College of Computer Science and Technology", faculty: "Information Technology" },
      { name: "School of Management", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-cn-ustc",
    name: "University of Science and Technology of China",
    shortName: "USTC",
    country: "China",
    countryCode: "CN",
    city: "Hefei",
    state: "Anhui",
    website: "https://en.ustc.edu.cn",
    domain: "ustc.edu.cn",
    timezone: "Asia/Shanghai",
    isVerified: true,
    campuses: [{ name: "East Main Campus", city: "Hefei", isMain: true }],
    departments: [
      { name: "School of Computer Science and Technology", faculty: "Information Science" },
      { name: "School of Physical Sciences", faculty: "Physical Sciences" },
    ],
  },

  // =========================================================================
  // HONG KONG (HK)
  // =========================================================================
  {
    seedKey: "seed-hk-hku",
    name: "The University of Hong Kong",
    shortName: "HKU",
    country: "Hong Kong",
    countryCode: "HK",
    city: "Hong Kong",
    website: "https://www.hku.hk",
    domain: "hku.hk",
    timezone: "Asia/Hong_Kong",
    isVerified: true,
    campuses: [{ name: "Pokfulam Main Campus", city: "Hong Kong", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Faculty of Engineering" },
      { name: "HKU Business School", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-hk-hkust",
    name: "The Hong Kong University of Science and Technology",
    shortName: "HKUST",
    country: "Hong Kong",
    countryCode: "HK",
    city: "Hong Kong",
    website: "https://hkust.edu.hk",
    domain: "hkust.edu.hk",
    timezone: "Asia/Hong_Kong",
    isVerified: true,
    campuses: [{ name: "Clear Water Bay Main Campus", city: "Hong Kong", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "School of Engineering" },
      { name: "School of Business and Management", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-hk-cuhk",
    name: "The Chinese University of Hong Kong",
    shortName: "CUHK",
    country: "Hong Kong",
    countryCode: "HK",
    city: "Hong Kong",
    website: "https://www.cuhk.edu.hk",
    domain: "cuhk.edu.hk",
    timezone: "Asia/Hong_Kong",
    isVerified: true,
    campuses: [{ name: "Shatin Main Campus", city: "Hong Kong", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "Faculty of Engineering" },
      { name: "CUHK Business School", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-hk-polyu",
    name: "The Hong Kong Polytechnic University",
    shortName: "PolyU",
    country: "Hong Kong",
    countryCode: "HK",
    city: "Hong Kong",
    website: "https://www.polyu.edu.hk",
    domain: "polyu.edu.hk",
    timezone: "Asia/Hong_Kong",
    isVerified: true,
    campuses: [{ name: "Hung Hom Main Campus", city: "Hong Kong", isMain: true }],
    departments: [
      { name: "Department of Computing", faculty: "Faculty of Computer and Mathematical Sciences" },
      { name: "Faculty of Business", faculty: "Business" },
    ],
  },

  // =========================================================================
  // TAIWAN (TW)
  // =========================================================================
  {
    seedKey: "seed-tw-ntu",
    name: "National Taiwan University",
    shortName: "NTU Taiwan",
    country: "Taiwan",
    countryCode: "TW",
    city: "Taipei",
    website: "https://www.ntu.edu.tw",
    domain: "ntu.edu.tw",
    timezone: "Asia/Taipei",
    isVerified: true,
    campuses: [{ name: "Daan Main Campus", city: "Taipei", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Information Engineering", faculty: "College of Electrical Engineering and Computer Science" },
      { name: "College of Management", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-tw-nthu",
    name: "National Tsing Hua University",
    shortName: "NTHU",
    country: "Taiwan",
    countryCode: "TW",
    city: "Hsinchu",
    website: "https://www.nthu.edu.tw",
    domain: "nthu.edu.tw",
    timezone: "Asia/Taipei",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Hsinchu", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "College of Electrical Engineering and Computer Science" },
      { name: "College of Science", faculty: "Science" },
    ],
  },
  {
    seedKey: "seed-tw-nycu",
    name: "National Yang Ming Chiao Tung University",
    shortName: "NYCU",
    country: "Taiwan",
    countryCode: "TW",
    city: "Hsinchu",
    website: "https://www.nycu.edu.tw",
    domain: "nycu.edu.tw",
    timezone: "Asia/Taipei",
    isVerified: true,
    campuses: [{ name: "Guangfu Main Campus", city: "Hsinchu", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "College of Computer Science" },
      { name: "College of Electrical and Computer Engineering", faculty: "Engineering" },
    ],
  },
];
