import { SeedUniversity } from "./types";

export const EUROPE_UNIVERSITIES: SeedUniversity[] = [
  // =========================================================================
  // UNITED KINGDOM (GB)
  // =========================================================================
  {
    seedKey: "seed-uk-oxford",
    name: "University of Oxford",
    shortName: "Oxford",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Oxford",
    state: "England",
    website: "https://www.ox.ac.uk",
    domain: "ox.ac.uk",
    timezone: "Europe/London",
    isVerified: true,
    campuses: [{ name: "Collegiate Main Campus", city: "Oxford", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Mathematical, Physical and Life Sciences" },
      { name: "Saïd Business School", faculty: "Social Sciences" },
      { name: "Department of Engineering Science", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-uk-cambridge",
    name: "University of Cambridge",
    shortName: "Cambridge",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Cambridge",
    state: "England",
    website: "https://www.cam.ac.uk",
    domain: "cam.ac.uk",
    timezone: "Europe/London",
    isVerified: true,
    campuses: [{ name: "Collegiate Main Campus", city: "Cambridge", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Technology", faculty: "Technology" },
      { name: "Cambridge Judge Business School", faculty: "Business" },
      { name: "Department of Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-uk-imperial",
    name: "Imperial College London",
    shortName: "Imperial",
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    state: "England",
    website: "https://www.imperial.ac.uk",
    domain: "imperial.ac.uk",
    timezone: "Europe/London",
    isVerified: true,
    campuses: [
      { name: "South Kensington Main Campus", city: "London", isMain: true },
      { name: "White City Campus", city: "London", isMain: false },
    ],
    departments: [
      { name: "Department of Computing", faculty: "Faculty of Engineering" },
      { name: "Department of Electrical and Electronic Engineering", faculty: "Faculty of Engineering" },
      { name: "Imperial College Business School", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-uk-ucl",
    name: "University College London",
    shortName: "UCL",
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    state: "England",
    website: "https://www.ucl.ac.uk",
    domain: "ucl.ac.uk",
    timezone: "Europe/London",
    isVerified: true,
    campuses: [
      { name: "Bloomsbury Main Campus", city: "London", isMain: true },
      { name: "UCL East Campus", city: "London", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Faculty of Engineering Sciences" },
      { name: "UCL School of Management", faculty: "Engineering Sciences" },
    ],
  },
  {
    seedKey: "seed-uk-edinburgh",
    name: "The University of Edinburgh",
    shortName: "Edinburgh",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Edinburgh",
    state: "Scotland",
    website: "https://www.ed.ac.uk",
    domain: "ed.ac.uk",
    timezone: "Europe/London",
    isVerified: true,
    campuses: [
      { name: "Central Area Main Campus", city: "Edinburgh", isMain: true },
      { name: "King's Buildings Campus", city: "Edinburgh", isMain: false },
    ],
    departments: [
      { name: "School of Informatics", faculty: "College of Science and Engineering" },
      { name: "University of Edinburgh Business School", faculty: "College of Arts, Humanities and Social Sciences" },
    ],
  },
  {
    seedKey: "seed-uk-manchester",
    name: "The University of Manchester",
    shortName: "UoM UK",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Manchester",
    state: "England",
    website: "https://www.manchester.ac.uk",
    domain: "manchester.ac.uk",
    timezone: "Europe/London",
    isVerified: true,
    campuses: [{ name: "Oxford Road Main Campus", city: "Manchester", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Faculty of Science and Engineering" },
      { name: "Alliance Manchester Business School", faculty: "Faculty of Humanities" },
    ],
  },
  {
    seedKey: "seed-uk-kcl",
    name: "King's College London",
    shortName: "KCL",
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    state: "England",
    website: "https://www.kcl.ac.uk",
    domain: "kcl.ac.uk",
    timezone: "Europe/London",
    isVerified: true,
    campuses: [
      { name: "Strand Main Campus", city: "London", isMain: true },
      { name: "Guy's Campus", city: "London", isMain: false },
      { name: "Waterloo Campus", city: "London", isMain: false },
    ],
    departments: [
      { name: "Department of Informatics", faculty: "Faculty of Natural, Mathematical & Engineering Sciences" },
      { name: "King's Business School", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-uk-lse",
    name: "London School of Economics and Political Science",
    shortName: "LSE UK",
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    state: "England",
    website: "https://www.lse.ac.uk",
    domain: "lse.ac.uk",
    timezone: "Europe/London",
    isVerified: true,
    campuses: [{ name: "Houghton Street Main Campus", city: "London", isMain: true }],
    departments: [
      { name: "Department of Economics", faculty: "Social Sciences" },
      { name: "Department of Management", faculty: "Social Sciences" },
      { name: "Department of Statistics / Data Science", faculty: "Mathematical Sciences" },
    ],
  },
  {
    seedKey: "seed-uk-bristol",
    name: "University of Bristol",
    shortName: "Bristol",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Bristol",
    state: "England",
    website: "https://www.bristol.ac.uk",
    domain: "bristol.ac.uk",
    timezone: "Europe/London",
    isVerified: true,
    campuses: [{ name: "Clifton Main Campus", city: "Bristol", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Faculty of Engineering" },
      { name: "School of Management", faculty: "Social Sciences" },
    ],
  },
  {
    seedKey: "seed-uk-warwick",
    name: "The University of Warwick",
    shortName: "Warwick",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Coventry",
    state: "England",
    website: "https://warwick.ac.uk",
    domain: "warwick.ac.uk",
    timezone: "Europe/London",
    isVerified: true,
    campuses: [{ name: "Gibbet Hill Main Campus", city: "Coventry", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Faculty of Science, Engineering and Medicine" },
      { name: "Warwick Business School (WBS)", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-uk-glasgow",
    name: "University of Glasgow",
    shortName: "Glasgow",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Glasgow",
    state: "Scotland",
    website: "https://www.gla.ac.uk",
    domain: "gla.ac.uk",
    timezone: "Europe/London",
    isVerified: true,
    campuses: [{ name: "Gilmorehill Main Campus", city: "Glasgow", isMain: true }],
    departments: [
      { name: "School of Computing Science", faculty: "College of Science and Engineering" },
      { name: "Adam Smith Business School", faculty: "College of Social Sciences" },
    ],
  },
  {
    seedKey: "seed-uk-birmingham",
    name: "University of Birmingham",
    shortName: "Birmingham",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Birmingham",
    state: "England",
    website: "https://www.birmingham.ac.uk",
    domain: "birmingham.ac.uk",
    timezone: "Europe/London",
    isVerified: true,
    campuses: [{ name: "Edgbaston Main Campus", city: "Birmingham", isMain: true }],
    departments: [
      { name: "School of Computer Science", faculty: "College of Engineering and Physical Sciences" },
      { name: "Birmingham Business School", faculty: "Social Sciences" },
    ],
  },
  {
    seedKey: "seed-uk-southampton",
    name: "University of Southampton",
    shortName: "Southampton",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Southampton",
    state: "England",
    website: "https://www.southampton.ac.uk",
    domain: "southampton.ac.uk",
    timezone: "Europe/London",
    isVerified: true,
    campuses: [{ name: "Highfield Main Campus", city: "Southampton", isMain: true }],
    departments: [
      { name: "School of Electronics and Computer Science (ECS)", faculty: "Faculty of Engineering and Physical Sciences" },
      { name: "Southampton Business School", faculty: "Business" },
    ],
  },

  // =========================================================================
  // SWITZERLAND (CH)
  // =========================================================================
  {
    seedKey: "seed-ch-eth",
    name: "ETH Zurich - Swiss Federal Institute of Technology",
    shortName: "ETH Zurich",
    country: "Switzerland",
    countryCode: "CH",
    city: "Zurich",
    state: "Zurich",
    website: "https://ethz.ch",
    domain: "ethz.ch",
    timezone: "Europe/Zurich",
    isVerified: true,
    campuses: [
      { name: "Zentrum Main Campus", city: "Zurich", isMain: true },
      { name: "Hönggerberg Campus", city: "Zurich", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science (D-INFK)", faculty: "Engineering Sciences" },
      { name: "Department of Information Technology and Electrical Engineering (D-ITET)", faculty: "Engineering Sciences" },
      { name: "Department of Management, Technology, and Economics (D-MTEC)", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-ch-epfl",
    name: "EPFL - École polytechnique fédérale de Lausanne",
    shortName: "EPFL",
    country: "Switzerland",
    countryCode: "CH",
    city: "Lausanne",
    state: "Vaud",
    website: "https://www.epfl.ch",
    domain: "epfl.ch",
    timezone: "Europe/Zurich",
    isVerified: true,
    campuses: [{ name: "Lausanne Main Campus", city: "Lausanne", isMain: true }],
    departments: [
      { name: "School of Computer and Communication Sciences (IC)", faculty: "Informatics & Communications" },
      { name: "School of Engineering (STI)", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-ch-uzh",
    name: "University of Zurich",
    shortName: "UZH",
    country: "Switzerland",
    countryCode: "CH",
    city: "Zurich",
    state: "Zurich",
    website: "https://www.uzh.ch",
    domain: "uzh.ch",
    timezone: "Europe/Zurich",
    isVerified: true,
    campuses: [{ name: "City Campus", city: "Zurich", isMain: true }],
    departments: [
      { name: "Department of Informatics", faculty: "Faculty of Business, Economics and Informatics" },
      { name: "Department of Banking and Finance", faculty: "Economics" },
    ],
  },
  {
    seedKey: "seed-ch-unige",
    name: "University of Geneva",
    shortName: "UNIGE",
    country: "Switzerland",
    countryCode: "CH",
    city: "Geneva",
    state: "Geneva",
    website: "https://www.unige.ch",
    domain: "unige.ch",
    timezone: "Europe/Zurich",
    isVerified: true,
    campuses: [{ name: "Uni Dufour Main Campus", city: "Geneva", isMain: true }],
    departments: [
      { name: "Computer Science Department", faculty: "Faculty of Science" },
      { name: "Geneva School of Economics and Management", faculty: "Management" },
    ],
  },

  // =========================================================================
  // GERMANY (DE)
  // =========================================================================
  {
    seedKey: "seed-de-tum",
    name: "Technical University of Munich",
    shortName: "TUM",
    country: "Germany",
    countryCode: "DE",
    city: "Munich",
    state: "Bavaria",
    website: "https://www.tum.de",
    domain: "tum.de",
    timezone: "Europe/Berlin",
    isVerified: true,
    campuses: [
      { name: "Munich City Main Campus", city: "Munich", isMain: true },
      { name: "Garching Campus", city: "Garching", isMain: false },
      { name: "Weihenstephan Campus", city: "Freising", isMain: false },
    ],
    departments: [
      { name: "TUM School of Computation, Information and Technology (CIT)", faculty: "Computation & IT" },
      { name: "TUM School of Engineering and Design (ED)", faculty: "Engineering" },
      { name: "TUM School of Management", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-de-lmu",
    name: "Ludwig Maximilian University of Munich",
    shortName: "LMU Munich",
    country: "Germany",
    countryCode: "DE",
    city: "Munich",
    state: "Bavaria",
    website: "https://www.lmu.de",
    domain: "lmu.de",
    timezone: "Europe/Berlin",
    isVerified: true,
    campuses: [{ name: "Geschwister-Scholl-Platz Main Campus", city: "Munich", isMain: true }],
    departments: [
      { name: "Institute of Informatics", faculty: "Faculty of Mathematics, Computer Science and Statistics" },
      { name: "Munich School of Management", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-de-heidelberg",
    name: "Heidelberg University",
    shortName: "Uni Heidelberg",
    country: "Germany",
    countryCode: "DE",
    city: "Heidelberg",
    state: "Baden-Württemberg",
    website: "https://www.uni-heidelberg.de",
    domain: "uni-heidelberg.de",
    timezone: "Europe/Berlin",
    isVerified: true,
    campuses: [{ name: "Neuenheimer Feld Campus", city: "Heidelberg", isMain: true }],
    departments: [
      { name: "Institute of Computer Science", faculty: "Faculty of Mathematics and Computer Science" },
      { name: "Medical Faculty Heidelberg", faculty: "Medicine" },
    ],
  },
  {
    seedKey: "seed-de-rwth",
    name: "RWTH Aachen University",
    shortName: "RWTH Aachen",
    country: "Germany",
    countryCode: "DE",
    city: "Aachen",
    state: "North Rhine-Westphalia",
    website: "https://www.rwth-aachen.de",
    domain: "rwth-aachen.de",
    timezone: "Europe/Berlin",
    isVerified: true,
    campuses: [{ name: "Aachen Main Campus", city: "Aachen", isMain: true }],
    departments: [
      { name: "Computer Science Department", faculty: "Faculty of Mathematics, Computer Science and Natural Sciences" },
      { name: "Faculty of Mechanical Engineering", faculty: "Engineering" },
      { name: "Faculty of Electrical Engineering and Information Technology", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-de-kit",
    name: "Karlsruhe Institute of Technology",
    shortName: "KIT",
    country: "Germany",
    countryCode: "DE",
    city: "Karlsruhe",
    state: "Baden-Württemberg",
    website: "https://www.kit.edu",
    domain: "kit.edu",
    timezone: "Europe/Berlin",
    isVerified: true,
    campuses: [
      { name: "Campus South", city: "Karlsruhe", isMain: true },
      { name: "Campus North", city: "Eggenstein-Leopoldshafen", isMain: false },
    ],
    departments: [
      { name: "KIT Department of Informatics", faculty: "Informatics" },
      { name: "KIT Department of Electrical Engineering and Information Technology", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-de-tu-berlin",
    name: "Technical University of Berlin",
    shortName: "TU Berlin",
    country: "Germany",
    countryCode: "DE",
    city: "Berlin",
    state: "Berlin",
    website: "https://www.tu.berlin",
    domain: "tu.berlin",
    timezone: "Europe/Berlin",
    isVerified: true,
    campuses: [{ name: "Charlottenburg Main Campus", city: "Berlin", isMain: true }],
    departments: [
      { name: "Faculty of Electrical Engineering and Computer Science (IV)", faculty: "Computer Science" },
      { name: "Faculty of Economics and Management", faculty: "Economics" },
    ],
  },
  {
    seedKey: "seed-de-humboldt",
    name: "Humboldt University of Berlin",
    shortName: "HU Berlin",
    country: "Germany",
    countryCode: "DE",
    city: "Berlin",
    state: "Berlin",
    website: "https://www.hu-berlin.de",
    domain: "hu-berlin.de",
    timezone: "Europe/Berlin",
    isVerified: true,
    campuses: [{ name: "Mitte Main Campus", city: "Berlin", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Faculty of Mathematics and Natural Sciences" },
      { name: "School of Business and Economics", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-de-stuttgart",
    name: "University of Stuttgart",
    shortName: "Uni Stuttgart",
    country: "Germany",
    countryCode: "DE",
    city: "Stuttgart",
    state: "Baden-Württemberg",
    website: "https://www.uni-stuttgart.de",
    domain: "uni-stuttgart.de",
    timezone: "Europe/Berlin",
    isVerified: true,
    campuses: [{ name: "Vaihingen Campus", city: "Stuttgart", isMain: true }],
    departments: [
      { name: "Faculty 5: Computer Science, Electrical Engineering and Information Technology", faculty: "Computer Science" },
      { name: "Faculty 7: Engineering Design, Production Engineering and Automotive Engineering", faculty: "Engineering" },
    ],
  },

  // =========================================================================
  // NETHERLANDS (NL)
  // =========================================================================
  {
    seedKey: "seed-nl-delft",
    name: "Delft University of Technology",
    shortName: "TU Delft",
    country: "Netherlands",
    countryCode: "NL",
    city: "Delft",
    state: "South Holland",
    website: "https://www.tudelft.nl",
    domain: "tudelft.nl",
    timezone: "Europe/Amsterdam",
    isVerified: true,
    campuses: [{ name: "TU Delft Main Campus", city: "Delft", isMain: true }],
    departments: [
      { name: "Faculty of Electrical Engineering, Mathematics and Computer Science (EEMCS)", faculty: "Computer Science & Engineering" },
      { name: "Faculty of Mechanical Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-nl-uva",
    name: "University of Amsterdam",
    shortName: "UvA",
    country: "Netherlands",
    countryCode: "NL",
    city: "Amsterdam",
    state: "North Holland",
    website: "https://www.uva.nl",
    domain: "uva.nl",
    timezone: "Europe/Amsterdam",
    isVerified: true,
    campuses: [
      { name: "Science Park Campus", city: "Amsterdam", isMain: true },
      { name: "Roeterseiland Campus", city: "Amsterdam", isMain: false },
    ],
    departments: [
      { name: "Informatics Institute", faculty: "Faculty of Science" },
      { name: "Amsterdam Business School", faculty: "Economics and Business" },
    ],
  },
  {
    seedKey: "seed-nl-eindhoven",
    name: "Eindhoven University of Technology",
    shortName: "TU/e",
    country: "Netherlands",
    countryCode: "NL",
    city: "Eindhoven",
    state: "North Brabant",
    website: "https://www.tue.nl",
    domain: "tue.nl",
    timezone: "Europe/Amsterdam",
    isVerified: true,
    campuses: [{ name: "TU/e Main Campus", city: "Eindhoven", isMain: true }],
    departments: [
      { name: "Department of Mathematics and Computer Science", faculty: "Computer Science" },
      { name: "Department of Electrical Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-nl-utrecht",
    name: "Utrecht University",
    shortName: "UU",
    country: "Netherlands",
    countryCode: "NL",
    city: "Utrecht",
    state: "Utrecht",
    website: "https://www.uu.nl",
    domain: "uu.nl",
    timezone: "Europe/Amsterdam",
    isVerified: true,
    campuses: [{ name: "Utrecht Science Park", city: "Utrecht", isMain: true }],
    departments: [
      { name: "Department of Information and Computing Sciences", faculty: "Faculty of Science" },
      { name: "Utrecht University School of Economics", faculty: "Law, Economics and Governance" },
    ],
  },
  {
    seedKey: "seed-nl-leiden",
    name: "Leiden University",
    shortName: "Leiden",
    country: "Netherlands",
    countryCode: "NL",
    city: "Leiden",
    state: "South Holland",
    website: "https://www.universiteitleiden.nl",
    domain: "universiteitleiden.nl",
    timezone: "Europe/Amsterdam",
    isVerified: true,
    campuses: [
      { name: "Leiden Campus", city: "Leiden", isMain: true },
      { name: "The Hague Campus", city: "The Hague", isMain: false },
    ],
    departments: [
      { name: "Leiden Institute of Advanced Computer Science (LIACS)", faculty: "Faculty of Science" },
      { name: "Leiden Law School", faculty: "Law" },
    ],
  },
  {
    seedKey: "seed-nl-erasmus",
    name: "Erasmus University Rotterdam",
    shortName: "EUR",
    country: "Netherlands",
    countryCode: "NL",
    city: "Rotterdam",
    state: "South Holland",
    website: "https://www.eur.nl",
    domain: "eur.nl",
    timezone: "Europe/Amsterdam",
    isVerified: true,
    campuses: [{ name: "Campus Woudestein", city: "Rotterdam", isMain: true }],
    departments: [
      { name: "Rotterdam School of Management (RSM)", faculty: "Management" },
      { name: "Erasmus School of Economics (ESE)", faculty: "Economics" },
    ],
  },

  // =========================================================================
  // FRANCE (FR)
  // =========================================================================
  {
    seedKey: "seed-fr-sorbonne",
    name: "Sorbonne University",
    shortName: "Sorbonne",
    country: "France",
    countryCode: "FR",
    city: "Paris",
    state: "Île-de-France",
    website: "https://www.sorbonne-universite.fr",
    domain: "sorbonne-universite.fr",
    timezone: "Europe/Paris",
    isVerified: true,
    campuses: [{ name: "Pierre and Marie Curie Campus (Jussieu)", city: "Paris", isMain: true }],
    departments: [
      { name: "Department of Computer Science (LIP6)", faculty: "Faculty of Science and Engineering" },
      { name: "Faculty of Arts and Humanities", faculty: "Humanities" },
    ],
  },
  {
    seedKey: "seed-fr-polytechnique",
    name: "École Polytechnique (Institut Polytechnique de Paris)",
    shortName: "l'X",
    country: "France",
    countryCode: "FR",
    city: "Palaiseau",
    state: "Île-de-France",
    website: "https://www.polytechnique.edu",
    domain: "polytechnique.edu",
    timezone: "Europe/Paris",
    isVerified: true,
    campuses: [{ name: "Palaiseau Campus", city: "Palaiseau", isMain: true }],
    departments: [
      { name: "Computer Science Laboratory (LIX)", faculty: "Computing and Mathematics" },
      { name: "Department of Applied Mathematics", faculty: "Mathematics" },
    ],
  },
  {
    seedKey: "seed-fr-psl",
    name: "Université PSL (Paris Sciences & Lettres)",
    shortName: "PSL",
    country: "France",
    countryCode: "FR",
    city: "Paris",
    state: "Île-de-France",
    website: "https://psl.eu",
    domain: "psl.eu",
    timezone: "Europe/Paris",
    isVerified: true,
    campuses: [{ name: "Latin Quarter Campus", city: "Paris", isMain: true }],
    departments: [
      { name: "ENS Department of Computer Science (DI ENS)", faculty: "Sciences" },
      { name: "Dauphine - Computer Science, Mathematics and Decision (MIDO)", faculty: "Informatics & Mathematics" },
    ],
  },
  {
    seedKey: "seed-fr-paris-saclay",
    name: "Université Paris-Saclay",
    shortName: "Paris-Saclay",
    country: "France",
    countryCode: "FR",
    city: "Orsay",
    state: "Île-de-France",
    website: "https://www.universite-paris-saclay.fr",
    domain: "universite-paris-saclay.fr",
    timezone: "Europe/Paris",
    isVerified: true,
    campuses: [{ name: "Orsay Campus", city: "Orsay", isMain: true }],
    departments: [
      { name: "Laboratoire Interdisciplinaire des Sciences du Numérique (LISN)", faculty: "Faculty of Sciences" },
      { name: "CentraleSupélec Computer Science Division", faculty: "Engineering" },
    ],
  },

  // =========================================================================
  // SWEDEN, DENMARK, FINLAND (SE, DK, FI)
  // =========================================================================
  {
    seedKey: "seed-se-kth",
    name: "KTH Royal Institute of Technology",
    shortName: "KTH",
    country: "Sweden",
    countryCode: "SE",
    city: "Stockholm",
    website: "https://www.kth.se",
    domain: "kth.se",
    timezone: "Europe/Stockholm",
    isVerified: true,
    campuses: [
      { name: "KTH Campus (Valhallavägen)", city: "Stockholm", isMain: true },
      { name: "Kista Campus (ICT)", city: "Kista", isMain: false },
    ],
    departments: [
      { name: "School of Electrical Engineering and Computer Science (EECS)", faculty: "EECS" },
      { name: "School of Engineering Sciences", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-se-lund",
    name: "Lund University",
    shortName: "Lund",
    country: "Sweden",
    countryCode: "SE",
    city: "Lund",
    state: "Skåne",
    website: "https://www.lunduniversity.lu.se",
    domain: "lu.se",
    timezone: "Europe/Stockholm",
    isVerified: true,
    campuses: [{ name: "Lund Main Campus", city: "Lund", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Faculty of Engineering (LTH)" },
      { name: "School of Economics and Management (LUSEM)", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-se-chalmers",
    name: "Chalmers University of Technology",
    shortName: "Chalmers",
    country: "Sweden",
    countryCode: "SE",
    city: "Gothenburg",
    website: "https://www.chalmers.se",
    domain: "chalmers.se",
    timezone: "Europe/Stockholm",
    isVerified: true,
    campuses: [{ name: "Johanneberg Main Campus", city: "Gothenburg", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "Engineering" },
      { name: "Department of Electrical Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-dk-copenhagen",
    name: "University of Copenhagen",
    shortName: "UCPH",
    country: "Denmark",
    countryCode: "DK",
    city: "Copenhagen",
    website: "https://www.ku.dk",
    domain: "ku.dk",
    timezone: "Europe/Copenhagen",
    isVerified: true,
    campuses: [{ name: "North Campus (Nørre Campus)", city: "Copenhagen", isMain: true }],
    departments: [
      { name: "Department of Computer Science (DIKU)", faculty: "Faculty of Science" },
      { name: "Faculty of Health and Medical Sciences", faculty: "Health" },
    ],
  },
  {
    seedKey: "seed-dk-dtu",
    name: "Technical University of Denmark",
    shortName: "DTU",
    country: "Denmark",
    countryCode: "DK",
    city: "Kongens Lyngby",
    website: "https://www.dtu.dk",
    domain: "dtu.dk",
    timezone: "Europe/Copenhagen",
    isVerified: true,
    campuses: [{ name: "Lyngby Main Campus", city: "Kongens Lyngby", isMain: true }],
    departments: [
      { name: "DTU Compute - Department of Applied Mathematics and Computer Science", faculty: "Computing" },
      { name: "DTU Electro", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-fi-aalto",
    name: "Aalto University",
    shortName: "Aalto",
    country: "Finland",
    countryCode: "FI",
    city: "Espoo",
    website: "https://www.aalto.fi",
    domain: "aalto.fi",
    timezone: "Europe/Helsinki",
    isVerified: true,
    campuses: [{ name: "Otaniemi Main Campus", city: "Espoo", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "School of Science" },
      { name: "School of Business", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-fi-helsinki",
    name: "University of Helsinki",
    shortName: "UH",
    country: "Finland",
    countryCode: "FI",
    city: "Helsinki",
    website: "https://www.helsinki.fi",
    domain: "helsinki.fi",
    timezone: "Europe/Helsinki",
    isVerified: true,
    campuses: [{ name: "Kumpula Science Campus", city: "Helsinki", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Faculty of Science" },
      { name: "Faculty of Social Sciences", faculty: "Social Sciences" },
    ],
  },

  // =========================================================================
  // IRELAND (IE)
  // =========================================================================
  {
    seedKey: "seed-ie-tcd",
    name: "Trinity College Dublin",
    shortName: "TCD",
    country: "Ireland",
    countryCode: "IE",
    city: "Dublin",
    website: "https://www.tcd.ie",
    domain: "tcd.ie",
    timezone: "Europe/Dublin",
    isVerified: true,
    campuses: [{ name: "College Green Main Campus", city: "Dublin", isMain: true }],
    departments: [
      { name: "School of Computer Science and Statistics", faculty: "Faculty of Science, Technology, Engineering and Mathematics" },
      { name: "Trinity Business School", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-ie-ucd",
    name: "University College Dublin",
    shortName: "UCD",
    country: "Ireland",
    countryCode: "IE",
    city: "Dublin",
    website: "https://www.ucd.ie",
    domain: "ucd.ie",
    timezone: "Europe/Dublin",
    isVerified: true,
    campuses: [{ name: "Belfield Main Campus", city: "Dublin", isMain: true }],
    departments: [
      { name: "UCD School of Computer Science", faculty: "College of Science" },
      { name: "UCD Michael Smurfit Graduate Business School", faculty: "Business" },
    ],
  },

  // =========================================================================
  // ITALY & SPAIN (IT, ES)
  // =========================================================================
  {
    seedKey: "seed-it-polimi",
    name: "Politecnico di Milano",
    shortName: "PoliMi",
    country: "Italy",
    countryCode: "IT",
    city: "Milan",
    state: "Lombardy",
    website: "https://www.polimi.it",
    domain: "polimi.it",
    timezone: "Europe/Rome",
    isVerified: true,
    campuses: [
      { name: "Campus Leonardo", city: "Milan", isMain: true },
      { name: "Campus Bovisa", city: "Milan", isMain: false },
    ],
    departments: [
      { name: "Dipartimento di Elettronica, Informazione e Bioingegneria (DEIB)", faculty: "Information Technology" },
      { name: "School of Industrial and Information Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-it-bologna",
    name: "University of Bologna",
    shortName: "UniBo",
    country: "Italy",
    countryCode: "IT",
    city: "Bologna",
    state: "Emilia-Romagna",
    website: "https://www.unibo.it",
    domain: "unibo.it",
    timezone: "Europe/Rome",
    isVerified: true,
    campuses: [{ name: "Bologna Main Campus", city: "Bologna", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering (DISI)", faculty: "Computer Science" },
      { name: "Department of Management", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-it-sapienza",
    name: "Sapienza University of Rome",
    shortName: "Sapienza",
    country: "Italy",
    countryCode: "IT",
    city: "Rome",
    state: "Lazio",
    website: "https://www.uniroma1.it",
    domain: "uniroma1.it",
    timezone: "Europe/Rome",
    isVerified: true,
    campuses: [{ name: "Città Universitaria Main Campus", city: "Rome", isMain: true }],
    departments: [
      { name: "Department of Computer Science (DI)", faculty: "Faculty of Information Engineering, Informatics and Statistics" },
      { name: "Department of Computer, Control, and Management Engineering (DIAG)", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-es-ub",
    name: "University of Barcelona",
    shortName: "UB",
    country: "Spain",
    countryCode: "ES",
    city: "Barcelona",
    state: "Catalonia",
    website: "https://www.ub.edu",
    domain: "ub.edu",
    timezone: "Europe/Madrid",
    isVerified: true,
    campuses: [{ name: "Plaça de la Universitat Main Campus", city: "Barcelona", isMain: true }],
    departments: [
      { name: "Department of Mathematics and Computer Science", faculty: "Faculty of Mathematics and Computer Science" },
      { name: "Faculty of Economics and Business", faculty: "Economics" },
    ],
  },
  {
    seedKey: "seed-es-upc",
    name: "Polytechnic University of Catalonia",
    shortName: "UPC / BarcelonaTech",
    country: "Spain",
    countryCode: "ES",
    city: "Barcelona",
    state: "Catalonia",
    website: "https://www.upc.edu",
    domain: "upc.edu",
    timezone: "Europe/Madrid",
    isVerified: true,
    campuses: [{ name: "Campus Nord Main Campus", city: "Barcelona", isMain: true }],
    departments: [
      { name: "Barcelona School of Informatics (FIB)", faculty: "Informatics" },
      { name: "Department of Computer Architecture", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-es-uam",
    name: "Autonomous University of Madrid",
    shortName: "UAM",
    country: "Spain",
    countryCode: "ES",
    city: "Madrid",
    state: "Community of Madrid",
    website: "https://www.uam.es",
    domain: "uam.es",
    timezone: "Europe/Madrid",
    isVerified: true,
    campuses: [{ name: "Cantoblanco Main Campus", city: "Madrid", isMain: true }],
    departments: [
      { name: "Higher Polytechnic School - Computer Science", faculty: "Engineering" },
      { name: "Faculty of Economics and Business Studies", faculty: "Business" },
    ],
  },

  // =========================================================================
  // BELGIUM & AUSTRIA (BE, AT)
  // =========================================================================
  {
    seedKey: "seed-be-kuleuven",
    name: "KU Leuven",
    shortName: "KU Leuven",
    country: "Belgium",
    countryCode: "BE",
    city: "Leuven",
    state: "Flanders",
    website: "https://www.kuleuven.be",
    domain: "kuleuven.be",
    timezone: "Europe/Brussels",
    isVerified: true,
    campuses: [{ name: "Leuven Main Campus", city: "Leuven", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Faculty of Engineering Science" },
      { name: "Faculty of Economics and Business (FEB)", faculty: "Economics" },
    ],
  },
  {
    seedKey: "seed-be-ghent",
    name: "Ghent University",
    shortName: "UGent",
    country: "Belgium",
    countryCode: "BE",
    city: "Ghent",
    state: "Flanders",
    website: "https://www.ugent.be",
    domain: "ugent.be",
    timezone: "Europe/Brussels",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Ghent", isMain: true }],
    departments: [
      { name: "Department of Applied Mathematics, Computer Science and Statistics", faculty: "Faculty of Sciences" },
      { name: "Faculty of Engineering and Architecture", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-at-univie",
    name: "University of Vienna",
    shortName: "UniVie",
    country: "Austria",
    countryCode: "AT",
    city: "Vienna",
    state: "Vienna",
    website: "https://www.univie.ac.at",
    domain: "univie.ac.at",
    timezone: "Europe/Vienna",
    isVerified: true,
    campuses: [{ name: "Universitätsring Main Campus", city: "Vienna", isMain: true }],
    departments: [
      { name: "Faculty of Computer Science", faculty: "Computer Science" },
      { name: "Faculty of Business, Economics and Statistics", faculty: "Economics" },
    ],
  },
  {
    seedKey: "seed-at-tuwien",
    name: "TU Wien (Vienna University of Technology)",
    shortName: "TU Wien",
    country: "Austria",
    countryCode: "AT",
    city: "Vienna",
    state: "Vienna",
    website: "https://www.tuwien.at",
    domain: "tuwien.at",
    timezone: "Europe/Vienna",
    isVerified: true,
    campuses: [{ name: "Karlsplatz Main Campus", city: "Vienna", isMain: true }],
    departments: [
      { name: "Faculty of Informatics", faculty: "Informatics" },
      { name: "Faculty of Electrical Engineering and Information Technology", faculty: "Engineering" },
    ],
  },
];
