import { SeedUniversity } from "./types";

export const MENA_UNIVERSITIES: SeedUniversity[] = [
  // =========================================================================
  // SAUDI ARABIA (SA)
  // =========================================================================
  {
    seedKey: "seed-sa-kfupm",
    name: "King Fahd University of Petroleum and Minerals",
    shortName: "KFUPM",
    country: "Saudi Arabia",
    countryCode: "SA",
    city: "Dhahran",
    state: "Eastern Province",
    website: "https://www.kfupm.edu.sa",
    domain: "kfupm.edu.sa",
    timezone: "Asia/Riyadh",
    isVerified: true,
    campuses: [{ name: "Dhahran Main Campus", city: "Dhahran", isMain: true }],
    departments: [
      { name: "College of Computing and Mathematics", faculty: "Computing" },
      { name: "College of Engineering and Physics", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-sa-ksu",
    name: "King Saud University",
    shortName: "KSU",
    country: "Saudi Arabia",
    countryCode: "SA",
    city: "Riyadh",
    state: "Riyadh Province",
    website: "https://ksu.edu.sa",
    domain: "ksu.edu.sa",
    timezone: "Asia/Riyadh",
    isVerified: true,
    campuses: [{ name: "Riyadh Main Campus", city: "Riyadh", isMain: true }],
    departments: [
      { name: "College of Computer and Information Sciences", faculty: "Computing" },
      { name: "College of Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-sa-kaust",
    name: "King Abdullah University of Science and Technology",
    shortName: "KAUST",
    country: "Saudi Arabia",
    countryCode: "SA",
    city: "Thuwal",
    state: "Makkah Province",
    website: "https://www.kaust.edu.sa",
    domain: "kaust.edu.sa",
    timezone: "Asia/Riyadh",
    isVerified: true,
    campuses: [{ name: "Thuwal Main Campus", city: "Thuwal", isMain: true }],
    departments: [
      { name: "Computer, Electrical and Mathematical Science and Engineering (CEMSE)", faculty: "Sciences & Engineering" },
      { name: "Physical Science and Engineering (PSE)", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-sa-kau",
    name: "King Abdulaziz University",
    shortName: "KAU",
    country: "Saudi Arabia",
    countryCode: "SA",
    city: "Jeddah",
    state: "Makkah Province",
    website: "https://www.kau.edu.sa",
    domain: "kau.edu.sa",
    timezone: "Asia/Riyadh",
    isVerified: true,
    campuses: [{ name: "Jeddah Main Campus", city: "Jeddah", isMain: true }],
    departments: [
      { name: "Faculty of Computing and Information Technology", faculty: "Computing" },
      { name: "Faculty of Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-sa-pnu",
    name: "Princess Nourah bint Abdulrahman University",
    shortName: "PNU",
    country: "Saudi Arabia",
    countryCode: "SA",
    city: "Riyadh",
    state: "Riyadh Province",
    website: "https://pnu.edu.sa",
    domain: "pnu.edu.sa",
    timezone: "Asia/Riyadh",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Riyadh", isMain: true }],
    departments: [
      { name: "College of Computer and Information Sciences", faculty: "Computing" },
      { name: "College of Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-sa-alfaisal",
    name: "Alfaisal University",
    shortName: "Alfaisal",
    country: "Saudi Arabia",
    countryCode: "SA",
    city: "Riyadh",
    state: "Riyadh Province",
    website: "https://www.alfaisal.edu",
    domain: "alfaisal.edu",
    timezone: "Asia/Riyadh",
    isVerified: true,
    campuses: [{ name: "Al Zahrawi Main Campus", city: "Riyadh", isMain: true }],
    departments: [
      { name: "College of Engineering - Software Engineering", faculty: "Engineering" },
      { name: "College of Business", faculty: "Business" },
    ],
  },

  // =========================================================================
  // UNITED ARAB EMIRATES (AE)
  // =========================================================================
  {
    seedKey: "seed-ae-uaeu",
    name: "United Arab Emirates University",
    shortName: "UAEU",
    country: "United Arab Emirates",
    countryCode: "AE",
    city: "Al Ain",
    state: "Abu Dhabi",
    website: "https://www.uaeu.ac.ae",
    domain: "uaeu.ac.ae",
    timezone: "Asia/Dubai",
    isVerified: true,
    campuses: [{ name: "Al Ain Main Campus", city: "Al Ain", isMain: true }],
    departments: [
      { name: "College of Information Technology", faculty: "Computing" },
      { name: "College of Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-ae-ku",
    name: "Khalifa University",
    shortName: "KU UAE",
    country: "United Arab Emirates",
    countryCode: "AE",
    city: "Abu Dhabi",
    state: "Abu Dhabi",
    website: "https://www.ku.ac.ae",
    domain: "ku.ac.ae",
    timezone: "Asia/Dubai",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Abu Dhabi", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Computing" },
      { name: "Department of Electrical Engineering and Computer Science", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-ae-aus",
    name: "American University of Sharjah",
    shortName: "AUS",
    country: "United Arab Emirates",
    countryCode: "AE",
    city: "Sharjah",
    state: "Sharjah",
    website: "https://www.aus.edu",
    domain: "aus.edu",
    timezone: "Asia/Dubai",
    isVerified: true,
    campuses: [{ name: "University City Main Campus", city: "Sharjah", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "Engineering" },
      { name: "School of Business Administration", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-ae-nyuad",
    name: "New York University Abu Dhabi",
    shortName: "NYU Abu Dhabi",
    country: "United Arab Emirates",
    countryCode: "AE",
    city: "Abu Dhabi",
    state: "Abu Dhabi",
    website: "https://nyuad.nyu.edu",
    domain: "nyu.edu",
    timezone: "Asia/Dubai",
    isVerified: true,
    campuses: [{ name: "Saadiyat Island Campus", city: "Abu Dhabi", isMain: true }],
    departments: [
      { name: "Division of Science - Computer Science", faculty: "Science" },
      { name: "Division of Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-ae-aud",
    name: "American University in Dubai",
    shortName: "AUD",
    country: "United Arab Emirates",
    countryCode: "AE",
    city: "Dubai",
    state: "Dubai",
    website: "https://www.aud.edu",
    domain: "aud.edu",
    timezone: "Asia/Dubai",
    isVerified: true,
    campuses: [{ name: "Dubai Media City Campus", city: "Dubai", isMain: true }],
    departments: [
      { name: "School of Engineering", faculty: "Engineering" },
      { name: "School of Business Administration", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-ae-birmingham",
    name: "University of Birmingham Dubai",
    shortName: "UoB Dubai",
    country: "United Arab Emirates",
    countryCode: "AE",
    city: "Dubai",
    state: "Dubai",
    website: "https://www.birmingham.ac.uk/dubai",
    domain: "birmingham.ac.uk",
    timezone: "Asia/Dubai",
    isVerified: true,
    campuses: [{ name: "Dubai International Academic City Campus", city: "Dubai", isMain: true }],
    departments: [
      { name: "School of Computer Science", faculty: "Engineering and Physical Sciences" },
      { name: "Birmingham Business School", faculty: "Business" },
    ],
  },

  // =========================================================================
  // QATAR (QA)
  // =========================================================================
  {
    seedKey: "seed-qa-qu",
    name: "Qatar University",
    shortName: "QU",
    country: "Qatar",
    countryCode: "QA",
    city: "Doha",
    state: "Ad Dawhah",
    website: "https://www.qu.edu.qa",
    domain: "qu.edu.qa",
    timezone: "Asia/Qatar",
    isVerified: true,
    campuses: [{ name: "Al Tarfa Main Campus", city: "Doha", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "College of Engineering" },
      { name: "College of Business and Economics", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-qa-cmuq",
    name: "Carnegie Mellon University in Qatar",
    shortName: "CMU-Q",
    country: "Qatar",
    countryCode: "QA",
    city: "Doha",
    state: "Ad Dawhah",
    website: "https://www.qatar.cmu.edu",
    domain: "cmu.edu",
    timezone: "Asia/Qatar",
    isVerified: true,
    campuses: [{ name: "Education City Campus", city: "Doha", isMain: true }],
    departments: [
      { name: "Computer Science Program", faculty: "Computing" },
      { name: "Information Systems Program", faculty: "Information Systems" },
    ],
  },
  {
    seedKey: "seed-qa-tamuq",
    name: "Texas A&M University at Qatar",
    shortName: "TAMUQ",
    country: "Qatar",
    countryCode: "QA",
    city: "Doha",
    state: "Ad Dawhah",
    website: "https://www.qatar.tamu.edu",
    domain: "tamu.edu",
    timezone: "Asia/Qatar",
    isVerified: true,
    campuses: [{ name: "Education City Campus", city: "Doha", isMain: true }],
    departments: [
      { name: "Electrical and Computer Engineering Program", faculty: "Engineering" },
      { name: "Chemical Engineering Program", faculty: "Engineering" },
    ],
  },

  // =========================================================================
  // TURKEY (TR)
  // =========================================================================
  {
    seedKey: "seed-tr-metu",
    name: "Middle East Technical University",
    shortName: "METU / ODTÜ",
    country: "Turkey",
    countryCode: "TR",
    city: "Ankara",
    state: "Ankara",
    website: "https://www.metu.edu.tr",
    domain: "metu.edu.tr",
    timezone: "Europe/Istanbul",
    isVerified: true,
    campuses: [
      { name: "Ankara Main Campus", city: "Ankara", isMain: true },
      { name: "Northern Cyprus Campus", city: "Kalkanli", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Engineering", faculty: "Faculty of Engineering" },
      { name: "Department of Electrical and Electronics Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-tr-bogazici",
    name: "Boğaziçi University",
    shortName: "BOUN",
    country: "Turkey",
    countryCode: "TR",
    city: "Istanbul",
    state: "Istanbul",
    website: "https://www.boun.edu.tr",
    domain: "boun.edu.tr",
    timezone: "Europe/Istanbul",
    isVerified: true,
    campuses: [
      { name: "South Campus (Bebek)", city: "Istanbul", isMain: true },
      { name: "North Campus", city: "Istanbul", isMain: false },
      { name: "Kandilli Campus", city: "Istanbul", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Engineering", faculty: "Faculty of Engineering" },
      { name: "Department of Management", faculty: "Faculty of Economics and Administrative Sciences" },
    ],
  },
  {
    seedKey: "seed-tr-itu",
    name: "Istanbul Technical University",
    shortName: "İTÜ",
    country: "Turkey",
    countryCode: "TR",
    city: "Istanbul",
    state: "Istanbul",
    website: "https://www.itu.edu.tr",
    domain: "itu.edu.tr",
    timezone: "Europe/Istanbul",
    isVerified: true,
    campuses: [
      { name: "Ayazağa Main Campus", city: "Istanbul", isMain: true },
      { name: "Maçka Campus", city: "Istanbul", isMain: false },
      { name: "Taşkışla Campus", city: "Istanbul", isMain: false },
    ],
    departments: [
      { name: "Faculty of Computer and Informatics Engineering", faculty: "Informatics" },
      { name: "Faculty of Electrical and Electronics Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-tr-bilkent",
    name: "Bilkent University",
    shortName: "Bilkent",
    country: "Turkey",
    countryCode: "TR",
    city: "Ankara",
    state: "Ankara",
    website: "https://www.bilkent.edu.tr",
    domain: "bilkent.edu.tr",
    timezone: "Europe/Istanbul",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Ankara", isMain: true }],
    departments: [
      { name: "Department of Computer Engineering", faculty: "Faculty of Engineering" },
      { name: "Faculty of Business Administration", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-tr-koc",
    name: "Koç University",
    shortName: "KU Turkey",
    country: "Turkey",
    countryCode: "TR",
    city: "Istanbul",
    state: "Istanbul",
    website: "https://www.ku.edu.tr",
    domain: "ku.edu.tr",
    timezone: "Europe/Istanbul",
    isVerified: true,
    campuses: [{ name: "Rumelifeneri Main Campus", city: "Istanbul", isMain: true }],
    departments: [
      { name: "College of Engineering - Computer Engineering", faculty: "Engineering" },
      { name: "College of Administrative Sciences and Economics", faculty: "Economics" },
    ],
  },
  {
    seedKey: "seed-tr-sabanci",
    name: "Sabancı University",
    shortName: "Sabancı",
    country: "Turkey",
    countryCode: "TR",
    city: "Istanbul",
    state: "Istanbul",
    website: "https://www.sabanciuniv.edu",
    domain: "sabanciuniv.edu",
    timezone: "Europe/Istanbul",
    isVerified: true,
    campuses: [{ name: "Tuzla Main Campus", city: "Istanbul", isMain: true }],
    departments: [
      { name: "Computer Science and Engineering Program", faculty: "Faculty of Engineering and Natural Sciences" },
      { name: "Sabancı Business School", faculty: "Business" },
    ],
  },

  // =========================================================================
  // EGYPT (EG)
  // =========================================================================
  {
    seedKey: "seed-eg-cairo",
    name: "Cairo University",
    shortName: "CU Egypt",
    country: "Egypt",
    countryCode: "EG",
    city: "Giza",
    state: "Giza Governorate",
    website: "https://cu.edu.eg",
    domain: "cu.edu.eg",
    timezone: "Africa/Cairo",
    isVerified: true,
    campuses: [
      { name: "Main Campus (Giza)", city: "Giza", isMain: true },
      { name: "Sheikh Zayed Campus", city: "6th of October", isMain: false },
    ],
    departments: [
      { name: "Faculty of Computers and Artificial Intelligence", faculty: "Computing" },
      { name: "Faculty of Engineering", faculty: "Engineering" },
      { name: "Kasr Al Ainy Faculty of Medicine", faculty: "Medicine" },
    ],
  },
  {
    seedKey: "seed-eg-auc",
    name: "The American University in Cairo",
    shortName: "AUC",
    country: "Egypt",
    countryCode: "EG",
    city: "Cairo",
    state: "Cairo Governorate",
    website: "https://www.aucegypt.edu",
    domain: "aucegypt.edu",
    timezone: "Africa/Cairo",
    isVerified: true,
    campuses: [
      { name: "New Cairo Main Campus", city: "New Cairo", isMain: true },
      { name: "Tahrir Square Campus", city: "Cairo", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "School of Sciences and Engineering" },
      { name: "School of Business", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-eg-ainshams",
    name: "Ain Shams University",
    shortName: "ASU Egypt",
    country: "Egypt",
    countryCode: "EG",
    city: "Cairo",
    state: "Cairo Governorate",
    website: "https://www.asu.edu.eg",
    domain: "asu.edu.eg",
    timezone: "Africa/Cairo",
    isVerified: true,
    campuses: [{ name: "Abbassia Main Campus", city: "Cairo", isMain: true }],
    departments: [
      { name: "Faculty of Computer and Information Sciences", faculty: "Computing" },
      { name: "Faculty of Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-eg-alexandria",
    name: "Alexandria University",
    shortName: "AlexU",
    country: "Egypt",
    countryCode: "EG",
    city: "Alexandria",
    state: "Alexandria Governorate",
    website: "https://alexu.edu.eg",
    domain: "alexu.edu.eg",
    timezone: "Africa/Cairo",
    isVerified: true,
    campuses: [{ name: "Chatby Main Campus", city: "Alexandria", isMain: true }],
    departments: [
      { name: "Faculty of Engineering - Computer and Systems Engineering", faculty: "Engineering" },
      { name: "Faculty of Science", faculty: "Sciences" },
    ],
  },
  {
    seedKey: "seed-eg-guc",
    name: "German University in Cairo",
    shortName: "GUC",
    country: "Egypt",
    countryCode: "EG",
    city: "New Cairo",
    state: "Cairo Governorate",
    website: "https://www.guc.edu.eg",
    domain: "guc.edu.eg",
    timezone: "Africa/Cairo",
    isVerified: true,
    campuses: [{ name: "New Cairo Main Campus", city: "New Cairo", isMain: true }],
    departments: [
      { name: "Faculty of Media Engineering and Technology (MET)", faculty: "Engineering & Computing" },
      { name: "Faculty of Information Engineering and Technology (IET)", faculty: "Engineering" },
    ],
  },

  // =========================================================================
  // LEBANON (LB)
  // =========================================================================
  {
    seedKey: "seed-lb-aub",
    name: "American University of Beirut",
    shortName: "AUB",
    country: "Lebanon",
    countryCode: "LB",
    city: "Beirut",
    state: "Beirut Governorate",
    website: "https://www.aub.edu.lb",
    domain: "aub.edu.lb",
    timezone: "Asia/Beirut",
    isVerified: true,
    campuses: [{ name: "Bliss Street Main Campus", city: "Beirut", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Faculty of Arts and Sciences" },
      { name: "Maroun Semaan Faculty of Engineering and Architecture (MSFEA)", faculty: "Engineering" },
      { name: "Suliman S. Olayan School of Business (OSB)", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-lb-lau",
    name: "Lebanese American University",
    shortName: "LAU",
    country: "Lebanon",
    countryCode: "LB",
    city: "Beirut",
    state: "Beirut Governorate",
    website: "https://www.lau.edu.lb",
    domain: "lau.edu.lb",
    timezone: "Asia/Beirut",
    isVerified: true,
    campuses: [
      { name: "Beirut Campus", city: "Beirut", isMain: true },
      { name: "Byblos Campus", city: "Byblos", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science and Mathematics", faculty: "Arts and Sciences" },
      { name: "School of Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-lb-usj",
    name: "Saint Joseph University of Beirut",
    shortName: "USJ",
    country: "Lebanon",
    countryCode: "LB",
    city: "Beirut",
    state: "Beirut Governorate",
    website: "https://www.usj.edu.lb",
    domain: "usj.edu.lb",
    timezone: "Asia/Beirut",
    isVerified: true,
    campuses: [{ name: "Campus des Sciences et Technologies", city: "Mar Roukos", isMain: true }],
    departments: [
      { name: "École Supérieure d'Ingénieurs de Beyrouth (ESIB)", faculty: "Engineering" },
      { name: "Faculté des Sciences", faculty: "Sciences" },
    ],
  },

  // =========================================================================
  // JORDAN (JO)
  // =========================================================================
  {
    seedKey: "seed-jo-uj",
    name: "University of Jordan",
    shortName: "UJ",
    country: "Jordan",
    countryCode: "JO",
    city: "Amman",
    state: "Amman Governorate",
    website: "https://www.ju.edu.jo",
    domain: "ju.edu.jo",
    timezone: "Asia/Amman",
    isVerified: true,
    campuses: [
      { name: "Amman Main Campus", city: "Amman", isMain: true },
      { name: "Aqaba Branch", city: "Aqaba", isMain: false },
    ],
    departments: [
      { name: "King Abdullah II School for Information Technology (KASIT)", faculty: "Computing" },
      { name: "School of Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-jo-just",
    name: "Jordan University of Science and Technology",
    shortName: "JUST",
    country: "Jordan",
    countryCode: "JO",
    city: "Irbid",
    state: "Irbid Governorate",
    website: "https://www.just.edu.jo",
    domain: "just.edu.jo",
    timezone: "Asia/Amman",
    isVerified: true,
    campuses: [{ name: "Ar-Ramtha Main Campus", city: "Irbid", isMain: true }],
    departments: [
      { name: "Faculty of Computer & Information Technology", faculty: "Computing" },
      { name: "Faculty of Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-jo-gju",
    name: "German Jordanian University",
    shortName: "GJU",
    country: "Jordan",
    countryCode: "JO",
    city: "Amman",
    state: "Madaba Governorate",
    website: "https://www.gju.edu.jo",
    domain: "gju.edu.jo",
    timezone: "Asia/Amman",
    isVerified: true,
    campuses: [{ name: "Mushaqar Main Campus", city: "Amman", isMain: true }],
    departments: [
      { name: "School of Applied Technical Sciences", faculty: "Applied Sciences" },
      { name: "School of Management and Logistic Sciences", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-jo-psut",
    name: "Princess Sumaya University for Technology",
    shortName: "PSUT",
    country: "Jordan",
    countryCode: "JO",
    city: "Amman",
    state: "Amman Governorate",
    website: "https://www.psut.edu.jo",
    domain: "psut.edu.jo",
    timezone: "Asia/Amman",
    isVerified: true,
    campuses: [{ name: "Jubaiha Main Campus", city: "Amman", isMain: true }],
    departments: [
      { name: "King Hussein School of Computing Sciences", faculty: "Computing" },
      { name: "King Abdullah II School of Engineering", faculty: "Engineering" },
    ],
  },
];
