import { SeedUniversity } from "./types";

export const OCEANIA_AFRICA_UNIVERSITIES: SeedUniversity[] = [
  // =========================================================================
  // AUSTRALIA (AU)
  // =========================================================================
  {
    seedKey: "seed-au-melbourne",
    name: "The University of Melbourne",
    shortName: "UniMelb",
    country: "Australia",
    countryCode: "AU",
    city: "Melbourne",
    state: "Victoria",
    website: "https://www.unimelb.edu.au",
    domain: "unimelb.edu.au",
    timezone: "Australia/Melbourne",
    isVerified: true,
    campuses: [
      { name: "Parkville Main Campus", city: "Melbourne", isMain: true },
      { name: "Southbank Campus", city: "Melbourne", isMain: false },
    ],
    departments: [
      { name: "School of Computing and Information Systems (CIS)", faculty: "Faculty of Engineering and Information Technology" },
      { name: "Melbourne Business School", faculty: "Business & Economics" },
    ],
  },
  {
    seedKey: "seed-au-sydney",
    name: "The University of Sydney",
    shortName: "USYD",
    country: "Australia",
    countryCode: "AU",
    city: "Sydney",
    state: "New South Wales",
    website: "https://www.sydney.edu.au",
    domain: "sydney.edu.au",
    timezone: "Australia/Sydney",
    isVerified: true,
    campuses: [{ name: "Camperdown/Darlington Main Campus", city: "Sydney", isMain: true }],
    departments: [
      { name: "School of Computer Science", faculty: "Faculty of Engineering" },
      { name: "University of Sydney Business School", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-au-anu",
    name: "The Australian National University",
    shortName: "ANU",
    country: "Australia",
    countryCode: "AU",
    city: "Canberra",
    state: "Australian Capital Territory",
    website: "https://www.anu.edu.au",
    domain: "anu.edu.au",
    timezone: "Australia/Sydney",
    isVerified: true,
    campuses: [{ name: "Acton Main Campus", city: "Canberra", isMain: true }],
    departments: [
      { name: "School of Computing", faculty: "College of Engineering, Computing and Cybernetics" },
      { name: "Research School of Management", faculty: "College of Business and Economics" },
    ],
  },
  {
    seedKey: "seed-au-unsw",
    name: "University of New South Wales",
    shortName: "UNSW Sydney",
    country: "Australia",
    countryCode: "AU",
    city: "Sydney",
    state: "New South Wales",
    website: "https://www.unsw.edu.au",
    domain: "unsw.edu.au",
    timezone: "Australia/Sydney",
    isVerified: true,
    campuses: [{ name: "Kensington Main Campus", city: "Sydney", isMain: true }],
    departments: [
      { name: "School of Computer Science and Engineering (CSE)", faculty: "Faculty of Engineering" },
      { name: "UNSW Business School", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-au-uq",
    name: "The University of Queensland",
    shortName: "UQ",
    country: "Australia",
    countryCode: "AU",
    city: "Brisbane",
    state: "Queensland",
    website: "https://www.uq.edu.au",
    domain: "uq.edu.au",
    timezone: "Australia/Brisbane",
    isVerified: true,
    campuses: [
      { name: "St Lucia Main Campus", city: "Brisbane", isMain: true },
      { name: "Gatton Campus", city: "Gatton", isMain: false },
    ],
    departments: [
      { name: "School of Information Technology and Electrical Engineering (ITEE)", faculty: "Faculty of Engineering, Architecture and Information Technology" },
      { name: "UQ Business School", faculty: "Business, Economics and Law" },
    ],
  },
  {
    seedKey: "seed-au-monash",
    name: "Monash University",
    shortName: "Monash",
    country: "Australia",
    countryCode: "AU",
    city: "Melbourne",
    state: "Victoria",
    website: "https://www.monash.edu",
    domain: "monash.edu",
    timezone: "Australia/Melbourne",
    isVerified: true,
    campuses: [
      { name: "Clayton Main Campus", city: "Melbourne", isMain: true },
      { name: "Caulfield Campus", city: "Melbourne", isMain: false },
    ],
    departments: [
      { name: "Faculty of Information Technology", faculty: "Information Technology" },
      { name: "Monash Business School", faculty: "Business and Economics" },
    ],
  },
  {
    seedKey: "seed-au-uwa",
    name: "The University of Western Australia",
    shortName: "UWA",
    country: "Australia",
    countryCode: "AU",
    city: "Perth",
    state: "Western Australia",
    website: "https://www.uwa.edu.au",
    domain: "uwa.edu.au",
    timezone: "Australia/Perth",
    isVerified: true,
    campuses: [{ name: "Crawley Main Campus", city: "Perth", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Software Engineering", faculty: "Faculty of Engineering and Mathematical Sciences" },
      { name: "UWA Business School", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-au-adelaide",
    name: "The University of Adelaide",
    shortName: "UofA",
    country: "Australia",
    countryCode: "AU",
    city: "Adelaide",
    state: "South Australia",
    website: "https://www.adelaide.edu.au",
    domain: "adelaide.edu.au",
    timezone: "Australia/Adelaide",
    isVerified: true,
    campuses: [{ name: "North Terrace Main Campus", city: "Adelaide", isMain: true }],
    departments: [
      { name: "School of Computer Science", faculty: "Faculty of Sciences, Engineering and Technology" },
      { name: "Adelaide Business School", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-au-uts",
    name: "University of Technology Sydney",
    shortName: "UTS",
    country: "Australia",
    countryCode: "AU",
    city: "Sydney",
    state: "New South Wales",
    website: "https://www.uts.edu.au",
    domain: "uts.edu.au",
    timezone: "Australia/Sydney",
    isVerified: true,
    campuses: [{ name: "City Campus (Ultimo)", city: "Sydney", isMain: true }],
    departments: [
      { name: "School of Computer Science", faculty: "Faculty of Engineering and Information Technology" },
      { name: "UTS Business School", faculty: "Business" },
    ],
  },

  // =========================================================================
  // NEW ZEALAND (NZ)
  // =========================================================================
  {
    seedKey: "seed-nz-auckland",
    name: "The University of Auckland",
    shortName: "UoA",
    country: "New Zealand",
    countryCode: "NZ",
    city: "Auckland",
    state: "Auckland",
    website: "https://www.auckland.ac.nz",
    domain: "auckland.ac.nz",
    timezone: "Pacific/Auckland",
    isVerified: true,
    campuses: [{ name: "City Main Campus", city: "Auckland", isMain: true }],
    departments: [
      { name: "School of Computer Science", faculty: "Faculty of Science" },
      { name: "University of Auckland Business School", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-nz-otago",
    name: "University of Otago",
    shortName: "Otago",
    country: "New Zealand",
    countryCode: "NZ",
    city: "Dunedin",
    state: "Otago",
    website: "https://www.otago.ac.nz",
    domain: "otago.ac.nz",
    timezone: "Pacific/Auckland",
    isVerified: true,
    campuses: [{ name: "Dunedin Main Campus", city: "Dunedin", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Sciences" },
      { name: "Otago Business School", faculty: "Commerce" },
    ],
  },
  {
    seedKey: "seed-nz-victoria",
    name: "Victoria University of Wellington",
    shortName: "VUW",
    country: "New Zealand",
    countryCode: "NZ",
    city: "Wellington",
    state: "Wellington",
    website: "https://www.wgtn.ac.nz",
    domain: "wgtn.ac.nz",
    timezone: "Pacific/Auckland",
    isVerified: true,
    campuses: [{ name: "Kelburn Main Campus", city: "Wellington", isMain: true }],
    departments: [
      { name: "School of Engineering and Computer Science", faculty: "Faculty of Engineering" },
      { name: "Wellington School of Business and Government", faculty: "Commerce" },
    ],
  },
  {
    seedKey: "seed-nz-canterbury",
    name: "University of Canterbury",
    shortName: "UC New Zealand",
    country: "New Zealand",
    countryCode: "NZ",
    city: "Christchurch",
    state: "Canterbury",
    website: "https://www.canterbury.ac.nz",
    domain: "canterbury.ac.nz",
    timezone: "Pacific/Auckland",
    isVerified: true,
    campuses: [{ name: "Ilam Main Campus", city: "Christchurch", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Software Engineering", faculty: "Faculty of Engineering" },
      { name: "UC Business School", faculty: "Business" },
    ],
  },

  // =========================================================================
  // SOUTH AFRICA (ZA)
  // =========================================================================
  {
    seedKey: "seed-za-uct",
    name: "University of Cape Town",
    shortName: "UCT",
    country: "South Africa",
    countryCode: "ZA",
    city: "Cape Town",
    state: "Western Cape",
    website: "https://www.uct.ac.za",
    domain: "uct.ac.za",
    timezone: "Africa/Johannesburg",
    isVerified: true,
    campuses: [{ name: "Rondebosch Main Campus", city: "Cape Town", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Faculty of Science" },
      { name: "Department of Information Systems", faculty: "Faculty of Commerce" },
      { name: "Faculty of Engineering & the Built Environment", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-za-wits",
    name: "University of the Witwatersrand",
    shortName: "Wits",
    country: "South Africa",
    countryCode: "ZA",
    city: "Johannesburg",
    state: "Gauteng",
    website: "https://www.wits.ac.za",
    domain: "wits.ac.za",
    timezone: "Africa/Johannesburg",
    isVerified: true,
    campuses: [{ name: "Braamfontein Main Campus", city: "Johannesburg", isMain: true }],
    departments: [
      { name: "School of Computer Science and Applied Mathematics (CSAM)", faculty: "Faculty of Science" },
      { name: "School of Electrical and Information Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-za-stellenbosch",
    name: "Stellenbosch University",
    shortName: "Maties",
    country: "South Africa",
    countryCode: "ZA",
    city: "Stellenbosch",
    state: "Western Cape",
    website: "https://www.sun.ac.za",
    domain: "sun.ac.za",
    timezone: "Africa/Johannesburg",
    isVerified: true,
    campuses: [{ name: "Stellenbosch Main Campus", city: "Stellenbosch", isMain: true }],
    departments: [
      { name: "Computer Science Division", faculty: "Faculty of Science" },
      { name: "Faculty of Economic and Management Sciences", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-za-pretoria",
    name: "University of Pretoria",
    shortName: "UP South Africa",
    country: "South Africa",
    countryCode: "ZA",
    city: "Pretoria",
    state: "Gauteng",
    website: "https://www.up.ac.za",
    domain: "up.ac.za",
    timezone: "Africa/Johannesburg",
    isVerified: true,
    campuses: [{ name: "Hatfield Main Campus", city: "Pretoria", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Faculty of Engineering, Built Environment and Information Technology" },
      { name: "Department of Informatics", faculty: "Information Technology" },
    ],
  },
  {
    seedKey: "seed-za-uj",
    name: "University of Johannesburg",
    shortName: "UJ",
    country: "South Africa",
    countryCode: "ZA",
    city: "Johannesburg",
    state: "Gauteng",
    website: "https://www.uj.ac.za",
    domain: "uj.ac.za",
    timezone: "Africa/Johannesburg",
    isVerified: true,
    campuses: [{ name: "Auckland Park Kingsway Main Campus", city: "Johannesburg", isMain: true }],
    departments: [
      { name: "Academy of Computer Science and Software Engineering", faculty: "Faculty of Science" },
      { name: "College of Business and Economics", faculty: "Business" },
    ],
  },

  // =========================================================================
  // NIGERIA (NG)
  // =========================================================================
  {
    seedKey: "seed-ng-ibadan",
    name: "University of Ibadan",
    shortName: "UI Nigeria",
    country: "Nigeria",
    countryCode: "NG",
    city: "Ibadan",
    state: "Oyo State",
    website: "https://ui.edu.ng",
    domain: "ui.edu.ng",
    timezone: "Africa/Lagos",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Ibadan", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Faculty of Science" },
      { name: "Faculty of Technology", faculty: "Technology" },
    ],
  },
  {
    seedKey: "seed-ng-unilag",
    name: "University of Lagos",
    shortName: "UNILAG",
    country: "Nigeria",
    countryCode: "NG",
    city: "Lagos",
    state: "Lagos State",
    website: "https://unilag.edu.ng",
    domain: "unilag.edu.ng",
    timezone: "Africa/Lagos",
    isVerified: true,
    campuses: [{ name: "Akoka Main Campus", city: "Lagos", isMain: true }],
    departments: [
      { name: "Department of Computer Sciences", faculty: "Faculty of Science" },
      { name: "Department of Electrical and Electronics Engineering", faculty: "Faculty of Engineering" },
    ],
  },
  {
    seedKey: "seed-ng-covenant",
    name: "Covenant University",
    shortName: "CU Nigeria",
    country: "Nigeria",
    countryCode: "NG",
    city: "Ota",
    state: "Ogun State",
    website: "https://covenantuniversity.edu.ng",
    domain: "covenantuniversity.edu.ng",
    timezone: "Africa/Lagos",
    isVerified: true,
    campuses: [{ name: "Canaanland Main Campus", city: "Ota", isMain: true }],
    departments: [
      { name: "Department of Computer and Information Sciences", faculty: "College of Science and Technology" },
      { name: "Department of Electrical and Information Engineering", faculty: "College of Engineering" },
    ],
  },
  {
    seedKey: "seed-ng-oau",
    name: "Obafemi Awolowo University",
    shortName: "OAU",
    country: "Nigeria",
    countryCode: "NG",
    city: "Ile-Ife",
    state: "Osun State",
    website: "https://oauife.edu.ng",
    domain: "oauife.edu.ng",
    timezone: "Africa/Lagos",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Ile-Ife", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "Faculty of Technology" },
      { name: "Department of Electronic and Electrical Engineering", faculty: "Technology" },
    ],
  },
  {
    seedKey: "seed-ng-abu",
    name: "Ahmadu Bello University",
    shortName: "ABU Zaria",
    country: "Nigeria",
    countryCode: "NG",
    city: "Zaria",
    state: "Kaduna State",
    website: "https://www.abu.edu.ng",
    domain: "abu.edu.ng",
    timezone: "Africa/Lagos",
    isVerified: true,
    campuses: [{ name: "Samaru Main Campus", city: "Zaria", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Faculty of Physical Sciences" },
      { name: "Faculty of Engineering", faculty: "Engineering" },
    ],
  },

  // =========================================================================
  // KENYA, GHANA, MOROCCO, UGANDA (KE, GH, MA, UG)
  // =========================================================================
  {
    seedKey: "seed-ke-uon",
    name: "University of Nairobi",
    shortName: "UoN",
    country: "Kenya",
    countryCode: "KE",
    city: "Nairobi",
    state: "Nairobi County",
    website: "https://uonbi.ac.ke",
    domain: "uonbi.ac.ke",
    timezone: "Africa/Nairobi",
    isVerified: true,
    campuses: [
      { name: "Main Campus (University Way)", city: "Nairobi", isMain: true },
      { name: "Chiromo Campus (Science)", city: "Nairobi", isMain: false },
    ],
    departments: [
      { name: "Department of Computing and Informatics (DCI)", faculty: "Faculty of Science and Technology" },
      { name: "Faculty of Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-ke-strathmore",
    name: "Strathmore University",
    shortName: "Strathmore",
    country: "Kenya",
    countryCode: "KE",
    city: "Nairobi",
    state: "Nairobi County",
    website: "https://strathmore.edu",
    domain: "strathmore.edu",
    timezone: "Africa/Nairobi",
    isVerified: true,
    campuses: [{ name: "Madaraka Main Campus", city: "Nairobi", isMain: true }],
    departments: [
      { name: "School of Computing and Engineering Sciences (SCES)", faculty: "Computing & Engineering" },
      { name: "Strathmore Business School (SBS)", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-ke-ku",
    name: "Kenyatta University",
    shortName: "KU Kenya",
    country: "Kenya",
    countryCode: "KE",
    city: "Nairobi",
    state: "Nairobi County",
    website: "https://www.ku.ac.ke",
    domain: "ku.ac.ke",
    timezone: "Africa/Nairobi",
    isVerified: true,
    campuses: [{ name: "Main Campus (Thika Road)", city: "Nairobi", isMain: true }],
    departments: [
      { name: "Department of Computing and Information Technology", faculty: "School of Engineering and Architecture" },
      { name: "School of Business, Economics and Tourism", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-gh-ug",
    name: "University of Ghana",
    shortName: "UG Legon",
    country: "Ghana",
    countryCode: "GH",
    city: "Accra",
    state: "Greater Accra Region",
    website: "https://www.ug.edu.gh",
    domain: "ug.edu.gh",
    timezone: "Africa/Accra",
    isVerified: true,
    campuses: [{ name: "Legon Main Campus", city: "Accra", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "School of Physical and Mathematical Sciences" },
      { name: "University of Ghana Business School (UGBS)", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-gh-knust",
    name: "Kwame Nkrumah University of Science and Technology",
    shortName: "KNUST",
    country: "Ghana",
    countryCode: "GH",
    city: "Kumasi",
    state: "Ashanti Region",
    website: "https://www.knust.edu.gh",
    domain: "knust.edu.gh",
    timezone: "Africa/Accra",
    isVerified: true,
    campuses: [{ name: "Kumasi Main Campus", city: "Kumasi", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "College of Science" },
      { name: "Department of Computer Engineering", faculty: "College of Engineering" },
    ],
  },
  {
    seedKey: "seed-ma-um6p",
    name: "Mohammed VI Polytechnic University",
    shortName: "UM6P",
    country: "Morocco",
    countryCode: "MA",
    city: "Benguerir",
    state: "Marrakesh-Safi",
    website: "https://um6p.ma",
    domain: "um6p.ma",
    timezone: "Africa/Casablanca",
    isVerified: true,
    campuses: [
      { name: "Benguerir Main Campus", city: "Benguerir", isMain: true },
      { name: "Rabat Campus", city: "Rabat", isMain: false },
    ],
    departments: [
      { name: "School of Computer Science (UM6P-CS)", faculty: "Computer Science & AI" },
      { name: "Africa Business School (ABS)", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-ug-mak",
    name: "Makerere University",
    shortName: "Mak",
    country: "Uganda",
    countryCode: "UG",
    city: "Kampala",
    state: "Central Region",
    website: "https://mak.ac.ug",
    domain: "mak.ac.ug",
    timezone: "Africa/Kampala",
    isVerified: true,
    campuses: [{ name: "Makerere Hill Main Campus", city: "Kampala", isMain: true }],
    departments: [
      { name: "School of Computing and Informatics Technology (CIT)", faculty: "College of Computing and Information Sciences" },
      { name: "College of Engineering, Design, Art and Technology (CEDAT)", faculty: "Engineering" },
    ],
  },
];
