import { SeedUniversity } from "./types";

export const PAKISTAN_UNIVERSITIES: SeedUniversity[] = [
  // =========================================================================
  // ISLAMABAD CAPITAL TERRITORY & RAWALPINDI
  // =========================================================================
  {
    seedKey: "seed-pk-nust",
    name: "National University of Sciences and Technology",
    shortName: "NUST",
    country: "Pakistan",
    countryCode: "PK",
    city: "Islamabad",
    state: "Federal Capital",
    website: "https://nust.edu.pk",
    domain: "nust.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus (H-12)", city: "Islamabad", isMain: true },
      { name: "CEME Campus", city: "Rawalpindi", isMain: false },
      { name: "CAE Campus", city: "Risalpur", isMain: false },
    ],
    departments: [
      { name: "School of Electrical Engineering and Computer Science (SEECS)", faculty: "Engineering & Computing" },
      { name: "School of Mechanical and Manufacturing Engineering (SMME)", faculty: "Engineering" },
      { name: "NUST Business School (NBS)", faculty: "Business & Management" },
      { name: "School of Civil and Environmental Engineering (SCEE)", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-pk-fast",
    name: "FAST National University of Computer and Emerging Sciences",
    shortName: "FAST-NUCES",
    country: "Pakistan",
    countryCode: "PK",
    city: "Islamabad",
    state: "Federal Capital",
    website: "https://nu.edu.pk",
    domain: "nu.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Islamabad Campus", city: "Islamabad", isMain: true },
      { name: "Lahore Campus", city: "Lahore", isMain: false },
      { name: "Karachi Campus", city: "Karachi", isMain: false },
      { name: "Peshawar Campus", city: "Peshawar", isMain: false },
      { name: "Faisalabad Campus", city: "Faisalabad", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Computing" },
      { name: "Department of Software Engineering", faculty: "Computing" },
      { name: "Department of Electrical Engineering", faculty: "Engineering" },
      { name: "Department of Management Sciences", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-pk-qau",
    name: "Quaid-i-Azam University",
    shortName: "QAU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Islamabad",
    state: "Federal Capital",
    website: "https://qau.edu.pk",
    domain: "qau.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Islamabad", isMain: true }],
    departments: [
      { name: "Faculty of Natural Sciences", faculty: "Sciences" },
      { name: "Faculty of Social Sciences", faculty: "Social Sciences" },
      { name: "Department of Computer Science", faculty: "Computing" },
    ],
  },
  {
    seedKey: "seed-pk-comsats",
    name: "COMSATS University Islamabad",
    shortName: "CUI",
    country: "Pakistan",
    countryCode: "PK",
    city: "Islamabad",
    state: "Federal Capital",
    website: "https://comsats.edu.pk",
    domain: "comsats.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Islamabad Campus", city: "Islamabad", isMain: true },
      { name: "Lahore Campus", city: "Lahore", isMain: false },
      { name: "Abbottabad Campus", city: "Abbottabad", isMain: false },
      { name: "Wah Campus", city: "Wah Cantt", isMain: false },
      { name: "Attock Campus", city: "Attock", isMain: false },
      { name: "Sahiwal Campus", city: "Sahiwal", isMain: false },
      { name: "Vehari Campus", city: "Vehari", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Information Sciences" },
      { name: "Department of Electrical and Computer Engineering", faculty: "Engineering" },
      { name: "Department of Management Sciences", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-pk-iiui",
    name: "International Islamic University, Islamabad",
    shortName: "IIUI",
    country: "Pakistan",
    countryCode: "PK",
    city: "Islamabad",
    state: "Federal Capital",
    website: "https://iiu.edu.pk",
    domain: "iiu.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "New Campus (Sector H-10)", city: "Islamabad", isMain: true },
      { name: "Faisal Mosque Old Campus", city: "Islamabad", isMain: false },
    ],
    departments: [
      { name: "Faculty of Computing and Information Technology", faculty: "Computing" },
      { name: "Faculty of Engineering and Technology", faculty: "Engineering" },
      { name: "Faculty of Management Sciences", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-pk-air",
    name: "Air University",
    shortName: "AU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Islamabad",
    state: "Federal Capital",
    website: "https://au.edu.pk",
    domain: "au.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Islamabad Main Campus", city: "Islamabad", isMain: true },
      { name: "Multan Campus", city: "Multan", isMain: false },
      { name: "Kamra Campus", city: "Kamra", isMain: false },
    ],
    departments: [
      { name: "Faculty of Computing and Artificial Intelligence", faculty: "Computing" },
      { name: "Faculty of Engineering", faculty: "Engineering" },
      { name: "Air University School of Management (AUSOM)", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-pk-bahria",
    name: "Bahria University",
    shortName: "BU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Islamabad",
    state: "Federal Capital",
    website: "https://bahria.edu.pk",
    domain: "bahria.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Islamabad Campus (E-8)", city: "Islamabad", isMain: true },
      { name: "Karachi Campus", city: "Karachi", isMain: false },
      { name: "Lahore Campus", city: "Lahore", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Computing" },
      { name: "Department of Software Engineering", faculty: "Computing" },
      { name: "Department of Business Studies", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-pk-pieas",
    name: "Pakistan Institute of Engineering and Applied Sciences",
    shortName: "PIEAS",
    country: "Pakistan",
    countryCode: "PK",
    city: "Islamabad",
    state: "Federal Capital",
    website: "https://pieas.edu.pk",
    domain: "pieas.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Nilore Main Campus", city: "Islamabad", isMain: true }],
    departments: [
      { name: "Department of Computer and Information Sciences (DCIS)", faculty: "Computing" },
      { name: "Department of Electrical Engineering", faculty: "Engineering" },
      { name: "Department of Nuclear Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-pk-ndu",
    name: "National Defence University",
    shortName: "NDU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Islamabad",
    state: "Federal Capital",
    website: "https://ndu.edu.pk",
    domain: "ndu.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus (E-9)", city: "Islamabad", isMain: true }],
    departments: [
      { name: "Faculty of Contemporary Studies", faculty: "Social Sciences" },
      { name: "Department of Strategic Studies", faculty: "Strategic Studies" },
    ],
  },
  {
    seedKey: "seed-pk-numl",
    name: "National University of Modern Languages",
    shortName: "NUML",
    country: "Pakistan",
    countryCode: "PK",
    city: "Islamabad",
    state: "Federal Capital",
    website: "https://numl.edu.pk",
    domain: "numl.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus (H-9)", city: "Islamabad", isMain: true },
      { name: "Lahore Campus", city: "Lahore", isMain: false },
      { name: "Karachi Campus", city: "Karachi", isMain: false },
    ],
    departments: [
      { name: "Faculty of Languages", faculty: "Languages" },
      { name: "Department of Computer Science", faculty: "Computing" },
      { name: "Faculty of Management Sciences", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-pk-riphah",
    name: "Riphah International University",
    shortName: "RIU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Islamabad",
    state: "Federal Capital",
    website: "https://riphah.edu.pk",
    domain: "riphah.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus (I-14)", city: "Islamabad", isMain: true },
      { name: "Al-Mizan Campus", city: "Rawalpindi", isMain: false },
      { name: "Lahore Campus", city: "Lahore", isMain: false },
    ],
    departments: [
      { name: "Faculty of Computing", faculty: "Computing" },
      { name: "Riphah College of Rehabilitation & Allied Health Sciences", faculty: "Medical" },
    ],
  },
  {
    seedKey: "seed-pk-shifa",
    name: "Shifa Tameer-e-Millat University",
    shortName: "STMU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Islamabad",
    state: "Federal Capital",
    website: "https://stmu.edu.pk",
    domain: "stmu.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus (H-8)", city: "Islamabad", isMain: true }],
    departments: [
      { name: "Shifa College of Medicine", faculty: "Medical Sciences" },
      { name: "Department of Computing", faculty: "Computing" },
    ],
  },
  {
    seedKey: "seed-pk-fjwu",
    name: "Fatima Jinnah Women University",
    shortName: "FJWU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Rawalpindi",
    state: "Punjab",
    website: "https://fjwu.edu.pk",
    domain: "fjwu.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Rawalpindi", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Computing" },
      { name: "Department of Business Administration", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-pk-rmu",
    name: "Rawalpindi Medical University",
    shortName: "RMU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Rawalpindi",
    state: "Punjab",
    website: "https://rmur.edu.pk",
    domain: "rmur.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Rawalpindi", isMain: true }],
    departments: [{ name: "Faculty of Medicine and Surgery", faculty: "Medicine" }],
  },
  {
    seedKey: "seed-pk-pmas",
    name: "Pir Mehr Ali Shah Arid Agriculture University",
    shortName: "PMAS-AAUR",
    country: "Pakistan",
    countryCode: "PK",
    city: "Rawalpindi",
    state: "Punjab",
    website: "https://uaar.edu.pk",
    domain: "uaar.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Rawalpindi", isMain: true }],
    departments: [
      { name: "Faculty of Sciences", faculty: "Sciences" },
      { name: "University Institute of Information Technology (UIIT)", faculty: "Computing" },
    ],
  },

  // =========================================================================
  // PUNJAB (Lahore, Faisalabad, Multan, Bahawalpur, Gujranwala, Sialkot, Sargodha, Taxila, Gujrat)
  // =========================================================================
  {
    seedKey: "seed-pk-lums",
    name: "Lahore University of Management Sciences",
    shortName: "LUMS",
    country: "Pakistan",
    countryCode: "PK",
    city: "Lahore",
    state: "Punjab",
    website: "https://lums.edu.pk",
    domain: "lums.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "DHA Main Campus", city: "Lahore", isMain: true }],
    departments: [
      { name: "Syed Babar Ali School of Science and Engineering (SBASSE)", faculty: "Science & Engineering" },
      { name: "Suleman Dawood School of Business (SDSB)", faculty: "Business" },
      { name: "Mushtaq Ahmad Gurmani School of Humanities and Social Sciences (MGSHSS)", faculty: "Humanities" },
      { name: "Shaikh Ahmad Hassan School of Law (SAHSL)", faculty: "Law" },
    ],
  },
  {
    seedKey: "seed-pk-pu",
    name: "University of the Punjab",
    shortName: "PU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Lahore",
    state: "Punjab",
    website: "https://pu.edu.pk",
    domain: "pu.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Quaid-i-Azam Campus (New Campus)", city: "Lahore", isMain: true },
      { name: "Allama Iqbal Campus (Old Campus)", city: "Lahore", isMain: false },
      { name: "Gujranwala Campus", city: "Gujranwala", isMain: false },
      { name: "Jhelum Campus", city: "Jhelum", isMain: false },
    ],
    departments: [
      { name: "Punjab University College of Information Technology (PUCIT)", faculty: "Computing" },
      { name: "Institute of Business Administration (IBA)", faculty: "Business" },
      { name: "Faculty of Engineering & Technology", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-pk-uet-lhr",
    name: "University of Engineering and Technology, Lahore",
    shortName: "UET Lahore",
    country: "Pakistan",
    countryCode: "PK",
    city: "Lahore",
    state: "Punjab",
    website: "https://uet.edu.pk",
    domain: "uet.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus (GT Road)", city: "Lahore", isMain: true },
      { name: "Kala Shah Kaku (KSK) Campus", city: "Lahore", isMain: false },
      { name: "Faisalabad Campus", city: "Faisalabad", isMain: false },
      { name: "Narowal Campus", city: "Narowal", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Computing" },
      { name: "Department of Electrical Engineering", faculty: "Engineering" },
      { name: "Department of Mechanical Engineering", faculty: "Engineering" },
      { name: "Department of Civil Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-pk-gcu-lhr",
    name: "Government College University, Lahore",
    shortName: "GCU Lahore",
    country: "Pakistan",
    countryCode: "PK",
    city: "Lahore",
    state: "Punjab",
    website: "https://gcu.edu.pk",
    domain: "gcu.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus", city: "Lahore", isMain: true },
      { name: "Kala Shah Kaku Campus", city: "Kala Shah Kaku", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Computing" },
      { name: "Department of Physics", faculty: "Physical Sciences" },
      { name: "Department of English", faculty: "Arts & Humanities" },
    ],
  },
  {
    seedKey: "seed-pk-itu",
    name: "Information Technology University of the Punjab",
    shortName: "ITU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Lahore",
    state: "Punjab",
    website: "https://itu.edu.pk",
    domain: "itu.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus (Arfa Software Technology Park)", city: "Lahore", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Computing" },
      { name: "Department of Electrical Engineering", faculty: "Engineering" },
      { name: "Department of Management and Technology", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-pk-fccu",
    name: "Forman Christian College (A Chartered University)",
    shortName: "FCCU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Lahore",
    state: "Punjab",
    website: "https://fccollege.edu.pk",
    domain: "fccollege.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus (Gulberg)", city: "Lahore", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Computer Science" },
      { name: "School of Management", faculty: "Business" },
      { name: "Department of Social Sciences", faculty: "Humanities" },
    ],
  },
  {
    seedKey: "seed-pk-umt",
    name: "University of Management and Technology",
    shortName: "UMT",
    country: "Pakistan",
    countryCode: "PK",
    city: "Lahore",
    state: "Punjab",
    website: "https://umt.edu.pk",
    domain: "umt.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus (Johar Town)", city: "Lahore", isMain: true },
      { name: "Sialkot Campus", city: "Sialkot", isMain: false },
    ],
    departments: [
      { name: "School of Systems and Technology (SST)", faculty: "Computing" },
      { name: "School of Business and Economics (SBE)", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-pk-ucp",
    name: "University of Central Punjab",
    shortName: "UCP",
    country: "Pakistan",
    countryCode: "PK",
    city: "Lahore",
    state: "Punjab",
    website: "https://ucp.edu.pk",
    domain: "ucp.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus (Johar Town)", city: "Lahore", isMain: true }],
    departments: [
      { name: "Faculty of Information Technology", faculty: "Computing" },
      { name: "Faculty of Engineering", faculty: "Engineering" },
      { name: "UCP Business School", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-pk-lse",
    name: "Lahore School of Economics",
    shortName: "LSE",
    country: "Pakistan",
    countryCode: "PK",
    city: "Lahore",
    state: "Punjab",
    website: "https://lahoreschoolofeconomics.edu.pk",
    domain: "lahoreschoolofeconomics.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus (Burki Road)", city: "Lahore", isMain: true }],
    departments: [
      { name: "Department of Economics", faculty: "Economics" },
      { name: "Department of Business Administration", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-pk-kemu",
    name: "King Edward Medical University",
    shortName: "KEMU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Lahore",
    state: "Punjab",
    website: "https://kemu.edu.pk",
    domain: "kemu.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Lahore", isMain: true }],
    departments: [{ name: "Faculty of Medicine and Allied Sciences", faculty: "Medicine" }],
  },
  {
    seedKey: "seed-pk-uhs",
    name: "University of Health Sciences, Lahore",
    shortName: "UHS",
    country: "Pakistan",
    countryCode: "PK",
    city: "Lahore",
    state: "Punjab",
    website: "https://uhs.edu.pk",
    domain: "uhs.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus (Khyaban-e-Jamia Punjab)", city: "Lahore", isMain: true }],
    departments: [{ name: "Department of Biomedical Sciences", faculty: "Health Sciences" }],
  },
  {
    seedKey: "seed-pk-uaf",
    name: "University of Agriculture, Faisalabad",
    shortName: "UAF",
    country: "Pakistan",
    countryCode: "PK",
    city: "Faisalabad",
    state: "Punjab",
    website: "https://uaf.edu.pk",
    domain: "uaf.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus", city: "Faisalabad", isMain: true },
      { name: "Burewala Campus", city: "Burewala", isMain: false },
      { name: "Toba Tek Singh Campus", city: "Toba Tek Singh", isMain: false },
    ],
    departments: [
      { name: "Faculty of Agriculture", faculty: "Agriculture" },
      { name: "Faculty of Sciences", faculty: "Sciences" },
      { name: "Department of Computer Science", faculty: "Computing" },
    ],
  },
  {
    seedKey: "seed-pk-gcuf",
    name: "Government College University Faisalabad",
    shortName: "GCUF",
    country: "Pakistan",
    countryCode: "PK",
    city: "Faisalabad",
    state: "Punjab",
    website: "https://gcuf.edu.pk",
    domain: "gcuf.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus (Kotwali Road)", city: "Faisalabad", isMain: true },
      { name: "New Campus (Jhang Road)", city: "Faisalabad", isMain: false },
    ],
    departments: [
      { name: "Faculty of Physical Sciences", faculty: "Physical Sciences" },
      { name: "Department of Computer Science", faculty: "Computing" },
    ],
  },
  {
    seedKey: "seed-pk-ntu",
    name: "National Textile University",
    shortName: "NTU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Faisalabad",
    state: "Punjab",
    website: "https://ntu.edu.pk",
    domain: "ntu.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus (Sheikhupura Road)", city: "Faisalabad", isMain: true },
      { name: "Karachi Campus", city: "Karachi", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Computing" },
      { name: "Faculty of Engineering and Technology", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-pk-bzu",
    name: "Bahauddin Zakariya University",
    shortName: "BZU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Multan",
    state: "Punjab",
    website: "https://bzu.edu.pk",
    domain: "bzu.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus (Bosan Road)", city: "Multan", isMain: true },
      { name: "Layyah Campus", city: "Layyah", isMain: false },
      { name: "Vehari Campus", city: "Vehari", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Computing" },
      { name: "Faculty of Engineering & Technology", faculty: "Engineering" },
      { name: "Institute of Management Sciences (IMS)", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-pk-nmu",
    name: "Nishtar Medical University",
    shortName: "NMU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Multan",
    state: "Punjab",
    website: "https://nmu.edu.pk",
    domain: "nmu.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Multan", isMain: true }],
    departments: [{ name: "Faculty of Medicine and Allied Sciences", faculty: "Medicine" }],
  },
  {
    seedKey: "seed-pk-iub",
    name: "The Islamia University of Bahawalpur",
    shortName: "IUB",
    country: "Pakistan",
    countryCode: "PK",
    city: "Bahawalpur",
    state: "Punjab",
    website: "https://iub.edu.pk",
    domain: "iub.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Baghdad-ul-Jadeed Campus", city: "Bahawalpur", isMain: true },
      { name: "Abbasia Campus", city: "Bahawalpur", isMain: false },
      { name: "Rahim Yar Khan Campus", city: "Rahim Yar Khan", isMain: false },
      { name: "Bahawalnagar Campus", city: "Bahawalnagar", isMain: false },
    ],
    departments: [
      { name: "Faculty of Computing", faculty: "Computing" },
      { name: "Faculty of Management Sciences", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-pk-uet-taxila",
    name: "University of Engineering and Technology, Taxila",
    shortName: "UET Taxila",
    country: "Pakistan",
    countryCode: "PK",
    city: "Taxila",
    state: "Punjab",
    website: "https://uettaxila.edu.pk",
    domain: "uettaxila.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus", city: "Taxila", isMain: true },
      { name: "Chakwal Sub-Campus", city: "Chakwal", isMain: false },
    ],
    departments: [
      { name: "Department of Software Engineering", faculty: "Computing" },
      { name: "Department of Computer Engineering", faculty: "Engineering" },
      { name: "Department of Electrical Engineering", faculty: "Engineering" },
      { name: "Department of Mechanical Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-pk-wah",
    name: "University of Wah",
    shortName: "UW",
    country: "Pakistan",
    countryCode: "PK",
    city: "Wah Cantt",
    state: "Punjab",
    website: "https://uow.edu.pk",
    domain: "uow.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Wah Cantt", isMain: true }],
    departments: [
      { name: "Faculty of Computer Science", faculty: "Computing" },
      { name: "Faculty of Management Sciences", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-pk-uos",
    name: "University of Sargodha",
    shortName: "UOS",
    country: "Pakistan",
    countryCode: "PK",
    city: "Sargodha",
    state: "Punjab",
    website: "https://su.edu.pk",
    domain: "su.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Sargodha", isMain: true }],
    departments: [
      { name: "Department of Computer Science & IT", faculty: "Computing" },
      { name: "Faculty of Sciences", faculty: "Sciences" },
    ],
  },
  {
    seedKey: "seed-pk-uog",
    name: "University of Gujrat",
    shortName: "UOG",
    country: "Pakistan",
    countryCode: "PK",
    city: "Gujrat",
    state: "Punjab",
    website: "https://uog.edu.pk",
    domain: "uog.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Hafiz Hayat Main Campus", city: "Gujrat", isMain: true },
      { name: "Mandi Bahauddin Campus", city: "Mandi Bahauddin", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Computing" },
      { name: "Faculty of Engineering and Technology", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-pk-uskt",
    name: "University of Sialkot",
    shortName: "USKT",
    country: "Pakistan",
    countryCode: "PK",
    city: "Sialkot",
    state: "Punjab",
    website: "https://uskt.edu.pk",
    domain: "uskt.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Sialkot", isMain: true }],
    departments: [
      { name: "Faculty of Computing & Information Technology", faculty: "Computing" },
      { name: "Faculty of Textile and Design", faculty: "Applied Sciences" },
    ],
  },

  // =========================================================================
  // SINDH (Karachi, Jamshoro/Hyderabad, Sukkur, Khairpur, Nawabshah, Tandojam)
  // =========================================================================
  {
    seedKey: "seed-pk-iba",
    name: "Institute of Business Administration, Karachi",
    shortName: "IBA Karachi",
    country: "Pakistan",
    countryCode: "PK",
    city: "Karachi",
    state: "Sindh",
    website: "https://iba.edu.pk",
    domain: "iba.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus (KU Circular Road)", city: "Karachi", isMain: true },
      { name: "City Campus (Garden Road)", city: "Karachi", isMain: false },
    ],
    departments: [
      { name: "School of Business Studies (SBS)", faculty: "Business" },
      { name: "School of Mathematics and Computer Science (SMCS)", faculty: "Computing & Mathematics" },
      { name: "School of Economics and Social Sciences (SESS)", faculty: "Social Sciences" },
    ],
  },
  {
    seedKey: "seed-pk-neduet",
    name: "NED University of Engineering and Technology",
    shortName: "NED UET",
    country: "Pakistan",
    countryCode: "PK",
    city: "Karachi",
    state: "Sindh",
    website: "https://neduet.edu.pk",
    domain: "neduet.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus (University Road)", city: "Karachi", isMain: true },
      { name: "City Campus", city: "Karachi", isMain: false },
      { name: "Thar Institute of Engineering (TIEST)", city: "Islamkot", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science & Information Technology", faculty: "Information Technology" },
      { name: "Department of Software Engineering", faculty: "Engineering" },
      { name: "Department of Electrical Engineering", faculty: "Engineering" },
      { name: "Department of Civil Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-pk-ku",
    name: "University of Karachi",
    shortName: "KU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Karachi",
    state: "Sindh",
    website: "https://uok.edu.pk",
    domain: "uok.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus (University Road)", city: "Karachi", isMain: true }],
    departments: [
      { name: "Department of Computer Science (UBIT)", faculty: "Computing" },
      { name: "Karachi University Business School (KUBS)", faculty: "Management" },
      { name: "Faculty of Science", faculty: "Sciences" },
    ],
  },
  {
    seedKey: "seed-pk-habib",
    name: "Habib University",
    shortName: "HU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Karachi",
    state: "Sindh",
    website: "https://habib.edu.pk",
    domain: "habib.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus (Gulistan-e-Jauhar)", city: "Karachi", isMain: true }],
    departments: [
      { name: "Dhanani School of Science and Engineering (DSSE)", faculty: "Science & Engineering" },
      { name: "School of Arts, Humanities and Social Sciences (AHSS)", faculty: "Humanities" },
    ],
  },
  {
    seedKey: "seed-pk-aku",
    name: "Aga Khan University",
    shortName: "AKU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Karachi",
    state: "Sindh",
    website: "https://aku.edu",
    domain: "aku.edu",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Stadium Road Main Campus", city: "Karachi", isMain: true }],
    departments: [
      { name: "Medical College", faculty: "Health Sciences" },
      { name: "School of Nursing and Midwifery", faculty: "Nursing" },
    ],
  },
  {
    seedKey: "seed-pk-duhs",
    name: "Dow University of Health Sciences",
    shortName: "DUHS",
    country: "Pakistan",
    countryCode: "PK",
    city: "Karachi",
    state: "Sindh",
    website: "https://duhs.edu.pk",
    domain: "duhs.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Ojha Campus", city: "Karachi", isMain: true },
      { name: "DMC Campus (Baba-e-Urdu Road)", city: "Karachi", isMain: false },
    ],
    departments: [
      { name: "Dow Medical College", faculty: "Medicine" },
      { name: "Dow College of Biotechnology", faculty: "Biotechnology" },
    ],
  },
  {
    seedKey: "seed-pk-iobm",
    name: "Institute of Business Management",
    shortName: "IoBM",
    country: "Pakistan",
    countryCode: "PK",
    city: "Karachi",
    state: "Sindh",
    website: "https://iobm.edu.pk",
    domain: "iobm.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Korangi Creek Main Campus", city: "Karachi", isMain: true }],
    departments: [
      { name: "College of Computer Science and Information Systems", faculty: "Computing" },
      { name: "College of Business Management", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-pk-szabist",
    name: "Shaheed Zulfiqar Ali Bhutto Institute of Science and Technology",
    shortName: "SZABIST",
    country: "Pakistan",
    countryCode: "PK",
    city: "Karachi",
    state: "Sindh",
    website: "https://szabist.edu.pk",
    domain: "szabist.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Karachi Clifton Campus", city: "Karachi", isMain: true },
      { name: "Islamabad Campus", city: "Islamabad", isMain: false },
      { name: "Hyderabad Campus", city: "Hyderabad", isMain: false },
      { name: "Larkana Campus", city: "Larkana", isMain: false },
    ],
    departments: [
      { name: "Faculty of Computing", faculty: "Computing" },
      { name: "Faculty of Management Sciences", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-pk-dawood",
    name: "Dawood University of Engineering and Technology",
    shortName: "DUET",
    country: "Pakistan",
    countryCode: "PK",
    city: "Karachi",
    state: "Sindh",
    website: "https://duet.edu.pk",
    domain: "duet.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus (New M.A. Jinnah Road)", city: "Karachi", isMain: true }],
    departments: [
      { name: "Department of Computer System Engineering", faculty: "Engineering" },
      { name: "Department of Electronic Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-pk-ziauddin",
    name: "Ziauddin University",
    shortName: "ZU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Karachi",
    state: "Sindh",
    website: "https://zu.edu.pk",
    domain: "zu.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Clifton Campus", city: "Karachi", isMain: true },
      { name: "Link Road Campus", city: "Karachi", isMain: false },
    ],
    departments: [
      { name: "Faculty of Health Sciences", faculty: "Health" },
      { name: "Faculty of Engineering, Science, Technology & Management", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-pk-muet",
    name: "Mehran University of Engineering and Technology",
    shortName: "MUET",
    country: "Pakistan",
    countryCode: "PK",
    city: "Jamshoro",
    state: "Sindh",
    website: "https://muet.edu.pk",
    domain: "muet.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus", city: "Jamshoro", isMain: true },
      { name: "SZAB Khairpur Mirs Campus", city: "Khairpur", isMain: false },
    ],
    departments: [
      { name: "Department of Software Engineering", faculty: "Electrical, Electronic & Computer Engineering" },
      { name: "Department of Computer Systems Engineering", faculty: "Engineering" },
      { name: "Department of Civil Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-pk-usindh",
    name: "University of Sindh",
    shortName: "UoS Jamshoro",
    country: "Pakistan",
    countryCode: "PK",
    city: "Jamshoro",
    state: "Sindh",
    website: "https://usindh.edu.pk",
    domain: "usindh.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Allama I.I. Kazi Main Campus", city: "Jamshoro", isMain: true },
      { name: "Elsa Kazi Campus", city: "Hyderabad", isMain: false },
      { name: "Mirpurkhas Campus", city: "Mirpurkhas", isMain: false },
    ],
    departments: [
      { name: "Institute of Mathematics and Computer Science", faculty: "Natural Sciences" },
      { name: "Institute of Business Administration", faculty: "Commerce & Business" },
    ],
  },
  {
    seedKey: "seed-pk-lumhs",
    name: "Liaquat University of Medical and Health Sciences",
    shortName: "LUMHS",
    country: "Pakistan",
    countryCode: "PK",
    city: "Jamshoro",
    state: "Sindh",
    website: "https://lumhs.edu.pk",
    domain: "lumhs.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Jamshoro", isMain: true }],
    departments: [{ name: "Faculty of Medicine and Allied Sciences", faculty: "Medicine" }],
  },
  {
    seedKey: "seed-pk-sau",
    name: "Sindh Agriculture University",
    shortName: "SAU Tandojam",
    country: "Pakistan",
    countryCode: "PK",
    city: "Tandojam",
    state: "Sindh",
    website: "https://sau.edu.pk",
    domain: "sau.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus", city: "Tandojam", isMain: true },
      { name: "Umerkot Campus", city: "Umerkot", isMain: false },
    ],
    departments: [
      { name: "Faculty of Crop Production", faculty: "Agriculture" },
      { name: "Information Technology Centre", faculty: "Computing" },
    ],
  },
  {
    seedKey: "seed-pk-sukkur-iba",
    name: "Sukkur IBA University",
    shortName: "SIBAU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Sukkur",
    state: "Sindh",
    website: "https://iba-suk.edu.pk",
    domain: "iba-suk.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus (Airport Road)", city: "Sukkur", isMain: true },
      { name: "Kandhkot Campus", city: "Kandhkot", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Computing" },
      { name: "Department of Business Administration", faculty: "Business" },
      { name: "Department of Electrical Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-pk-salu",
    name: "Shah Abdul Latif University",
    shortName: "SALU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Khairpur",
    state: "Sindh",
    website: "https://salu.edu.pk",
    domain: "salu.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus", city: "Khairpur", isMain: true },
      { name: "Shikarpur Campus", city: "Shikarpur", isMain: false },
      { name: "Ghotki Campus", city: "Ghotki", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Physical Sciences" },
      { name: "Department of Commerce", faculty: "Commerce" },
    ],
  },
  {
    seedKey: "seed-pk-quest",
    name: "Quaid-e-Awam University of Engineering, Sciences and Technology",
    shortName: "QUEST",
    country: "Pakistan",
    countryCode: "PK",
    city: "Nawabshah",
    state: "Sindh",
    website: "https://quest.edu.pk",
    domain: "quest.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus", city: "Nawabshah", isMain: true },
      { name: "Larkana Campus", city: "Larkana", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Systems Engineering", faculty: "Engineering" },
      { name: "Department of Electrical Engineering", faculty: "Engineering" },
    ],
  },

  // =========================================================================
  // KHYBER PAKHTUNKHWA (Peshawar, Topi, Abbottabad, Kohat, Malakand, Swat, Mardan, D.I. Khan, Bannu)
  // =========================================================================
  {
    seedKey: "seed-pk-uet-pesh",
    name: "University of Engineering and Technology, Peshawar",
    shortName: "UET Peshawar",
    country: "Pakistan",
    countryCode: "PK",
    city: "Peshawar",
    state: "Khyber Pakhtunkhwa",
    website: "https://uetpeshawar.edu.pk",
    domain: "uetpeshawar.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus", city: "Peshawar", isMain: true },
      { name: "Jalozai Campus", city: "Nowshera", isMain: false },
      { name: "Bannu Campus", city: "Bannu", isMain: false },
      { name: "Kohat Campus", city: "Kohat", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Systems Engineering", faculty: "Electrical & Computer Engineering" },
      { name: "Department of Computer Science and Information Technology", faculty: "Computing" },
      { name: "Department of Electrical Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-pk-uop",
    name: "University of Peshawar",
    shortName: "UOP",
    country: "Pakistan",
    countryCode: "PK",
    city: "Peshawar",
    state: "Khyber Pakhtunkhwa",
    website: "https://uop.edu.pk",
    domain: "uop.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Peshawar", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Numerical & Physical Sciences" },
      { name: "Institute of Management Studies", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-pk-giki",
    name: "Ghulam Ishaq Khan Institute of Engineering Sciences and Technology",
    shortName: "GIKI",
    country: "Pakistan",
    countryCode: "PK",
    city: "Topi",
    state: "Khyber Pakhtunkhwa",
    website: "https://giki.edu.pk",
    domain: "giki.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Topi Main Campus", city: "Topi", isMain: true }],
    departments: [
      { name: "Faculty of Computer Science and Engineering (FCSE)", faculty: "Computing" },
      { name: "Faculty of Electrical Engineering (FEE)", faculty: "Engineering" },
      { name: "Faculty of Mechanical Engineering (FME)", faculty: "Engineering" },
      { name: "Department of Management Sciences and Humanities", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-pk-imsciences",
    name: "Institute of Management Sciences, Peshawar",
    shortName: "IMSciences",
    country: "Pakistan",
    countryCode: "PK",
    city: "Peshawar",
    state: "Khyber Pakhtunkhwa",
    website: "https://imsciences.edu.pk",
    domain: "imsciences.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Hayatabad Main Campus", city: "Peshawar", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Computing" },
      { name: "Department of Management Sciences", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-pk-kmu",
    name: "Khyber Medical University",
    shortName: "KMU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Peshawar",
    state: "Khyber Pakhtunkhwa",
    website: "https://kmu.edu.pk",
    domain: "kmu.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Hayatabad Main Campus", city: "Peshawar", isMain: true }],
    departments: [{ name: "Institute of Medical Sciences", faculty: "Health Sciences" }],
  },
  {
    seedKey: "seed-pk-icp",
    name: "Islamia College Peshawar",
    shortName: "ICP",
    country: "Pakistan",
    countryCode: "PK",
    city: "Peshawar",
    state: "Khyber Pakhtunkhwa",
    website: "https://icp.edu.pk",
    domain: "icp.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Peshawar", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Computing" },
      { name: "Department of Management Sciences", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-pk-cecos",
    name: "CECOS University of Information Technology and Emerging Sciences",
    shortName: "CECOS",
    country: "Pakistan",
    countryCode: "PK",
    city: "Peshawar",
    state: "Khyber Pakhtunkhwa",
    website: "https://cecos.edu.pk",
    domain: "cecos.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Hayatabad Main Campus", city: "Peshawar", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Computing" },
      { name: "Department of Civil Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-pk-aust",
    name: "Abbottabad University of Science and Technology",
    shortName: "AUST",
    country: "Pakistan",
    countryCode: "PK",
    city: "Abbottabad",
    state: "Khyber Pakhtunkhwa",
    website: "https://aust.edu.pk",
    domain: "aust.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Havelian Main Campus", city: "Abbottabad", isMain: true }],
    departments: [
      { name: "Department of Information Technology", faculty: "Computing" },
      { name: "Department of Pharmacy", faculty: "Medical" },
    ],
  },
  {
    seedKey: "seed-pk-kust",
    name: "Kohat University of Science and Technology",
    shortName: "KUST",
    country: "Pakistan",
    countryCode: "PK",
    city: "Kohat",
    state: "Khyber Pakhtunkhwa",
    website: "https://kust.edu.pk",
    domain: "kust.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Kohat", isMain: true }],
    departments: [
      { name: "Institute of Computing", faculty: "Computing" },
      { name: "Institute of Management Sciences", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-pk-uom",
    name: "University of Malakand",
    shortName: "UOM",
    country: "Pakistan",
    countryCode: "PK",
    city: "Chakdara",
    state: "Khyber Pakhtunkhwa",
    website: "https://uom.edu.pk",
    domain: "uom.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Chakdara", isMain: true }],
    departments: [
      { name: "Department of Computer Science & IT", faculty: "Computing" },
      { name: "Department of Management Studies", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-pk-uswat",
    name: "University of Swat",
    shortName: "UOSwat",
    country: "Pakistan",
    countryCode: "PK",
    city: "Swat",
    state: "Khyber Pakhtunkhwa",
    website: "https://uswat.edu.pk",
    domain: "uswat.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Charbagh Main Campus", city: "Swat", isMain: true }],
    departments: [
      { name: "Department of Computer and Software Technology", faculty: "Computing" },
      { name: "Department of Economics", faculty: "Social Sciences" },
    ],
  },
  {
    seedKey: "seed-pk-hazara",
    name: "Hazara University",
    shortName: "HU Mansehra",
    country: "Pakistan",
    countryCode: "PK",
    city: "Mansehra",
    state: "Khyber Pakhtunkhwa",
    website: "https://hu.edu.pk",
    domain: "hu.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Dhodial Main Campus", city: "Mansehra", isMain: true },
      { name: "Battagram Campus", city: "Battagram", isMain: false },
    ],
    departments: [
      { name: "Department of Information Technology", faculty: "Computing" },
      { name: "Department of Management Sciences", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-pk-awkum",
    name: "Abdul Wali Khan University Mardan",
    shortName: "AWKUM",
    country: "Pakistan",
    countryCode: "PK",
    city: "Mardan",
    state: "Khyber Pakhtunkhwa",
    website: "https://awkum.edu.pk",
    domain: "awkum.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Garden Main Campus", city: "Mardan", isMain: true },
      { name: "Pabbi Campus", city: "Nowshera", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Computing" },
      { name: "Faculty of Physical & Numerical Sciences", faculty: "Sciences" },
    ],
  },
  {
    seedKey: "seed-pk-gomal",
    name: "Gomal University",
    shortName: "GU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Dera Ismail Khan",
    state: "Khyber Pakhtunkhwa",
    website: "https://gu.edu.pk",
    domain: "gu.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Dera Ismail Khan", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Computing" },
      { name: "Faculty of Agriculture", faculty: "Agriculture" },
    ],
  },
  {
    seedKey: "seed-pk-ustb",
    name: "University of Science and Technology Bannu",
    shortName: "USTB",
    country: "Pakistan",
    countryCode: "PK",
    city: "Bannu",
    state: "Khyber Pakhtunkhwa",
    website: "https://ustb.edu.pk",
    domain: "ustb.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Bannu", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Computing" },
      { name: "Department of Electrical Engineering", faculty: "Engineering" },
    ],
  },

  // =========================================================================
  // BALOCHISTAN (Quetta, Khuzdar, Uthal, Turbat, Loralai)
  // =========================================================================
  {
    seedKey: "seed-pk-buitems",
    name: "Balochistan University of Information Technology, Engineering and Management Sciences",
    shortName: "BUITEMS",
    country: "Pakistan",
    countryCode: "PK",
    city: "Quetta",
    state: "Balochistan",
    website: "https://buitms.edu.pk",
    domain: "buitms.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Takatu Main Campus (Baleli)", city: "Quetta", isMain: true },
      { name: "City Campus (Jinnah Town)", city: "Quetta", isMain: false },
      { name: "Muslim Bagh Sub-Campus", city: "Muslim Bagh", isMain: false },
    ],
    departments: [
      { name: "Faculty of Information and Communication Technology (FICT)", faculty: "Computing" },
      { name: "Faculty of Engineering & Architecture", faculty: "Engineering" },
      { name: "Faculty of Management Sciences", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-pk-uob",
    name: "University of Balochistan",
    shortName: "UOB",
    country: "Pakistan",
    countryCode: "PK",
    city: "Quetta",
    state: "Balochistan",
    website: "https://uob.edu.pk",
    domain: "uob.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Sariab Road Main Campus", city: "Quetta", isMain: true },
      { name: "Mastung Sub-Campus", city: "Mastung", isMain: false },
      { name: "Kharan Sub-Campus", city: "Kharan", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science & IT", faculty: "Physical Sciences" },
      { name: "Department of Commerce", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-pk-sbkwu",
    name: "Sardar Bahadur Khan Women's University",
    shortName: "SBKWU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Quetta",
    state: "Balochistan",
    website: "https://sbkwu.edu.pk",
    domain: "sbkwu.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus (Brewery Road)", city: "Quetta", isMain: true },
      { name: "Nushki Sub-Campus", city: "Nushki", isMain: false },
      { name: "Khuzdar Sub-Campus", city: "Khuzdar", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Basic Sciences" },
      { name: "Department of Management Sciences", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-pk-buetk",
    name: "Balochistan University of Engineering and Technology, Khuzdar",
    shortName: "BUET Khuzdar",
    country: "Pakistan",
    countryCode: "PK",
    city: "Khuzdar",
    state: "Balochistan",
    website: "https://buetk.edu.pk",
    domain: "buetk.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Khuzdar", isMain: true }],
    departments: [
      { name: "Department of Computer Systems Engineering", faculty: "Engineering" },
      { name: "Department of Electrical Engineering", faculty: "Engineering" },
      { name: "Department of Civil Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-pk-luawms",
    name: "Lasbela University of Agriculture, Water and Marine Sciences",
    shortName: "LUAWMS",
    country: "Pakistan",
    countryCode: "PK",
    city: "Uthal",
    state: "Balochistan",
    website: "https://luawms.edu.pk",
    domain: "luawms.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Uthal", isMain: true }],
    departments: [
      { name: "Faculty of Marine Sciences", faculty: "Marine Sciences" },
      { name: "Department of Computer Science", faculty: "Basic Sciences" },
    ],
  },
  {
    seedKey: "seed-pk-bumhs",
    name: "Bolan University of Medical and Health Sciences",
    shortName: "BUMHS",
    country: "Pakistan",
    countryCode: "PK",
    city: "Quetta",
    state: "Balochistan",
    website: "https://bumhs.edu.pk",
    domain: "bumhs.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Quetta", isMain: true }],
    departments: [{ name: "Faculty of Medicine", faculty: "Medical Sciences" }],
  },
  {
    seedKey: "seed-pk-turbat",
    name: "University of Turbat",
    shortName: "UoT",
    country: "Pakistan",
    countryCode: "PK",
    city: "Turbat",
    state: "Balochistan",
    website: "https://uot.edu.pk",
    domain: "uot.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Turbat", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Computing" },
      { name: "Department of Management Sciences", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-pk-loralai",
    name: "University of Loralai",
    shortName: "UoLo",
    country: "Pakistan",
    countryCode: "PK",
    city: "Loralai",
    state: "Balochistan",
    website: "https://uoli.edu.pk",
    domain: "uoli.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Loralai", isMain: true }],
    departments: [
      { name: "Department of Computer Science", faculty: "Computing" },
      { name: "Department of Management Sciences", faculty: "Management" },
    ],
  },

  // =========================================================================
  // AZAD JAMMU & KASHMIR (AJK)
  // =========================================================================
  {
    seedKey: "seed-pk-uajk",
    name: "University of Azad Jammu and Kashmir",
    shortName: "UAJK",
    country: "Pakistan",
    countryCode: "PK",
    city: "Muzaffarabad",
    state: "Azad Jammu & Kashmir",
    website: "https://ajku.edu.pk",
    domain: "ajku.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Chehla Bandi Main Campus", city: "Muzaffarabad", isMain: true },
      { name: "City Campus", city: "Muzaffarabad", isMain: false },
      { name: "Neelum Campus", city: "Athmuqam", isMain: false },
      { name: "Jhelum Valley Campus", city: "Hattian Bala", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science & IT", faculty: "Sciences" },
      { name: "Kashmir Institute of Economics", faculty: "Social Sciences" },
    ],
  },
  {
    seedKey: "seed-pk-must",
    name: "Mirpur University of Science and Technology",
    shortName: "MUST",
    country: "Pakistan",
    countryCode: "PK",
    city: "Mirpur",
    state: "Azad Jammu & Kashmir",
    website: "https://must.edu.pk",
    domain: "must.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus (Allama Iqbal Road)", city: "Mirpur", isMain: true },
      { name: "Bhimber Campus", city: "Bhimber", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science and Information Technology", faculty: "Computing" },
      { name: "Department of Software Engineering", faculty: "Engineering" },
      { name: "Department of Electrical Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-pk-poonch",
    name: "University of Poonch Rawalakot",
    shortName: "UoPR",
    country: "Pakistan",
    countryCode: "PK",
    city: "Rawalakot",
    state: "Azad Jammu & Kashmir",
    website: "https://upr.edu.pk",
    domain: "upr.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Main Campus", city: "Rawalakot", isMain: true },
      { name: "Hajira Campus", city: "Hajira", isMain: false },
      { name: "Mong Campus", city: "Mong", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Basic & Applied Sciences" },
      { name: "Faculty of Agriculture", faculty: "Agriculture" },
    ],
  },
  {
    seedKey: "seed-pk-uok-ajk",
    name: "University of Kotli Azad Jammu and Kashmir",
    shortName: "UOK AJK",
    country: "Pakistan",
    countryCode: "PK",
    city: "Kotli",
    state: "Azad Jammu & Kashmir",
    website: "https://uokajk.edu.pk",
    domain: "uokajk.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Kotli", isMain: true }],
    departments: [
      { name: "Department of Computer Science & IT", faculty: "Computing" },
      { name: "Faculty of Management Sciences", faculty: "Business" },
    ],
  },

  // =========================================================================
  // GILGIT-BALTISTAN (GB)
  // =========================================================================
  {
    seedKey: "seed-pk-kiu",
    name: "Karakoram International University",
    shortName: "KIU",
    country: "Pakistan",
    countryCode: "PK",
    city: "Gilgit",
    state: "Gilgit-Baltistan",
    website: "https://kiu.edu.pk",
    domain: "kiu.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Gilgit Main Campus", city: "Gilgit", isMain: true },
      { name: "Skardu Sub-Campus", city: "Skardu", isMain: false },
      { name: "Hunza Sub-Campus", city: "Aliabad", isMain: false },
      { name: "Ghizer Sub-Campus", city: "Gupis", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Life Sciences & Computing" },
      { name: "Department of Business Management", faculty: "Social Sciences" },
      { name: "Department of Mining Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-pk-uobs",
    name: "University of Baltistan, Skardu",
    shortName: "UOBS",
    country: "Pakistan",
    countryCode: "PK",
    city: "Skardu",
    state: "Gilgit-Baltistan",
    website: "https://uobs.edu.pk",
    domain: "uobs.edu.pk",
    timezone: "Asia/Karachi",
    isVerified: true,
    campuses: [
      { name: "Hussainabad Main Campus", city: "Skardu", isMain: true },
      { name: "Sundus City Campus", city: "Skardu", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science", faculty: "Natural Sciences" },
      { name: "Department of Business Management", faculty: "Management" },
    ],
  },
];
