import { SeedUniversity } from "./types";

export const SOUTH_ASIA_UNIVERSITIES: SeedUniversity[] = [
  // =========================================================================
  // INDIA (IN)
  // =========================================================================
  {
    seedKey: "seed-in-iitb",
    name: "Indian Institute of Technology Bombay",
    shortName: "IIT Bombay",
    country: "India",
    countryCode: "IN",
    city: "Mumbai",
    state: "Maharashtra",
    website: "https://www.iitb.ac.in",
    domain: "iitb.ac.in",
    timezone: "Asia/Kolkata",
    isVerified: true,
    campuses: [{ name: "Powai Main Campus", city: "Mumbai", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "Engineering" },
      { name: "Department of Electrical Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-in-iitd",
    name: "Indian Institute of Technology Delhi",
    shortName: "IIT Delhi",
    country: "India",
    countryCode: "IN",
    city: "New Delhi",
    state: "Delhi",
    website: "https://home.iitd.ac.in",
    domain: "iitd.ac.in",
    timezone: "Asia/Kolkata",
    isVerified: true,
    campuses: [{ name: "Hauz Khas Main Campus", city: "New Delhi", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "Engineering" },
      { name: "Department of Management Studies", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-in-iitm",
    name: "Indian Institute of Technology Madras",
    shortName: "IIT Madras",
    country: "India",
    countryCode: "IN",
    city: "Chennai",
    state: "Tamil Nadu",
    website: "https://www.iitm.ac.in",
    domain: "iitm.ac.in",
    timezone: "Asia/Kolkata",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Chennai", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "Engineering" },
      { name: "Department of Mechanical Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-in-iitk",
    name: "Indian Institute of Technology Kanpur",
    shortName: "IIT Kanpur",
    country: "India",
    countryCode: "IN",
    city: "Kanpur",
    state: "Uttar Pradesh",
    website: "https://www.iitk.ac.in",
    domain: "iitk.ac.in",
    timezone: "Asia/Kolkata",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Kanpur", isMain: true }],
    departments: [
      { name: "Department of Computer Science & Engineering", faculty: "Engineering" },
      { name: "Department of Electrical Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-in-iitkgp",
    name: "Indian Institute of Technology Kharagpur",
    shortName: "IIT Kharagpur",
    country: "India",
    countryCode: "IN",
    city: "Kharagpur",
    state: "West Bengal",
    website: "https://www.iitkgp.ac.in",
    domain: "iitkgp.ac.in",
    timezone: "Asia/Kolkata",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Kharagpur", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "Computing" },
      { name: "Department of Electronics and Electrical Communication Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-in-iisc",
    name: "Indian Institute of Science Bangalore",
    shortName: "IISc Bangalore",
    country: "India",
    countryCode: "IN",
    city: "Bangalore",
    state: "Karnataka",
    website: "https://iisc.ac.in",
    domain: "iisc.ac.in",
    timezone: "Asia/Kolkata",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Bangalore", isMain: true }],
    departments: [
      { name: "Department of Computational and Data Sciences", faculty: "Sciences" },
      { name: "Department of Computer Science and Automation", faculty: "Computing" },
    ],
  },
  {
    seedKey: "seed-in-iima",
    name: "Indian Institute of Management Ahmedabad",
    shortName: "IIM Ahmedabad",
    country: "India",
    countryCode: "IN",
    city: "Ahmedabad",
    state: "Gujarat",
    website: "https://www.iima.ac.in",
    domain: "iima.ac.in",
    timezone: "Asia/Kolkata",
    isVerified: true,
    campuses: [{ name: "Vastrapur Main Campus", city: "Ahmedabad", isMain: true }],
    departments: [{ name: "Business and Management Studies", faculty: "Management" }],
  },
  {
    seedKey: "seed-in-iimb",
    name: "Indian Institute of Management Bangalore",
    shortName: "IIM Bangalore",
    country: "India",
    countryCode: "IN",
    city: "Bangalore",
    state: "Karnataka",
    website: "https://www.iimb.ac.in",
    domain: "iimb.ac.in",
    timezone: "Asia/Kolkata",
    isVerified: true,
    campuses: [{ name: "Bannerghatta Main Campus", city: "Bangalore", isMain: true }],
    departments: [{ name: "Management Education", faculty: "Business" }],
  },
  {
    seedKey: "seed-in-du",
    name: "University of Delhi",
    shortName: "DU",
    country: "India",
    countryCode: "IN",
    city: "New Delhi",
    state: "Delhi",
    website: "https://www.du.ac.in",
    domain: "du.ac.in",
    timezone: "Asia/Kolkata",
    isVerified: true,
    campuses: [
      { name: "North Campus", city: "New Delhi", isMain: true },
      { name: "South Campus", city: "New Delhi", isMain: false },
    ],
    departments: [
      { name: "Faculty of Mathematical Sciences", faculty: "Sciences" },
      { name: "Faculty of Technology", faculty: "Technology" },
    ],
  },
  {
    seedKey: "seed-in-jnu",
    name: "Jawaharlal Nehru University",
    shortName: "JNU",
    country: "India",
    countryCode: "IN",
    city: "New Delhi",
    state: "Delhi",
    website: "https://www.jnu.ac.in",
    domain: "jnu.ac.in",
    timezone: "Asia/Kolkata",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "New Delhi", isMain: true }],
    departments: [
      { name: "School of Computer and Systems Sciences", faculty: "Computing" },
      { name: "School of International Studies", faculty: "Social Sciences" },
    ],
  },
  {
    seedKey: "seed-in-bhu",
    name: "Banaras Hindu University",
    shortName: "BHU",
    country: "India",
    countryCode: "IN",
    city: "Varanasi",
    state: "Uttar Pradesh",
    website: "https://www.bhu.ac.in",
    domain: "bhu.ac.in",
    timezone: "Asia/Kolkata",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Varanasi", isMain: true }],
    departments: [
      { name: "Institute of Science", faculty: "Sciences" },
      { name: "Faculty of Commerce", faculty: "Commerce" },
    ],
  },
  {
    seedKey: "seed-in-amu",
    name: "Aligarh Muslim University",
    shortName: "AMU",
    country: "India",
    countryCode: "IN",
    city: "Aligarh",
    state: "Uttar Pradesh",
    website: "https://www.amu.ac.in",
    domain: "amu.ac.in",
    timezone: "Asia/Kolkata",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Aligarh", isMain: true }],
    departments: [
      { name: "Zakir Husain College of Engineering & Technology", faculty: "Engineering" },
      { name: "Department of Computer Science", faculty: "Science" },
    ],
  },
  {
    seedKey: "seed-in-bits",
    name: "Birla Institute of Technology and Science, Pilani",
    shortName: "BITS Pilani",
    country: "India",
    countryCode: "IN",
    city: "Pilani",
    state: "Rajasthan",
    website: "https://www.bits-pilani.ac.in",
    domain: "bits-pilani.ac.in",
    timezone: "Asia/Kolkata",
    isVerified: true,
    campuses: [
      { name: "Pilani Campus", city: "Pilani", isMain: true },
      { name: "Goa Campus", city: "Zuarinagar", isMain: false },
      { name: "Hyderabad Campus", city: "Hyderabad", isMain: false },
    ],
    departments: [
      { name: "Department of Computer Science and Information Systems", faculty: "Computing" },
      { name: "Department of Electrical and Electronics Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-in-iiith",
    name: "International Institute of Information Technology, Hyderabad",
    shortName: "IIIT Hyderabad",
    country: "India",
    countryCode: "IN",
    city: "Hyderabad",
    state: "Telangana",
    website: "https://www.iiit.ac.in",
    domain: "iiit.ac.in",
    timezone: "Asia/Kolkata",
    isVerified: true,
    campuses: [{ name: "Gachibowli Main Campus", city: "Hyderabad", isMain: true }],
    departments: [
      { name: "Kohli Center on Intelligent Systems", faculty: "Computing & AI" },
      { name: "Computer Science and Engineering Division", faculty: "Computing" },
    ],
  },
  {
    seedKey: "seed-in-nitt",
    name: "National Institute of Technology, Tiruchirappalli",
    shortName: "NIT Trichy",
    country: "India",
    countryCode: "IN",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    website: "https://www.nitt.edu",
    domain: "nitt.edu",
    timezone: "Asia/Kolkata",
    isVerified: true,
    campuses: [{ name: "Thuvakudi Main Campus", city: "Tiruchirappalli", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "Engineering" },
      { name: "Department of Management Studies", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-in-nitk",
    name: "National Institute of Technology Karnataka, Surathkal",
    shortName: "NITK Surathkal",
    country: "India",
    countryCode: "IN",
    city: "Surathkal",
    state: "Karnataka",
    website: "https://www.nitk.ac.in",
    domain: "nitk.ac.in",
    timezone: "Asia/Kolkata",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Surathkal", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "Engineering" },
      { name: "Department of Information Technology", faculty: "Computing" },
    ],
  },
  {
    seedKey: "seed-in-vit",
    name: "Vellore Institute of Technology",
    shortName: "VIT",
    country: "India",
    countryCode: "IN",
    city: "Vellore",
    state: "Tamil Nadu",
    website: "https://vit.ac.in",
    domain: "vit.ac.in",
    timezone: "Asia/Kolkata",
    isVerified: true,
    campuses: [
      { name: "Vellore Main Campus", city: "Vellore", isMain: true },
      { name: "Chennai Campus", city: "Chennai", isMain: false },
    ],
    departments: [
      { name: "School of Computer Science and Engineering (SCOPE)", faculty: "Computing" },
      { name: "School of Information Technology and Engineering (SITE)", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-in-manipal",
    name: "Manipal Academy of Higher Education",
    shortName: "MAHE",
    country: "India",
    countryCode: "IN",
    city: "Manipal",
    state: "Karnataka",
    website: "https://manipal.edu",
    domain: "manipal.edu",
    timezone: "Asia/Kolkata",
    isVerified: true,
    campuses: [
      { name: "Manipal Main Campus", city: "Manipal", isMain: true },
      { name: "Mangalore Campus", city: "Mangalore", isMain: false },
    ],
    departments: [
      { name: "Manipal Institute of Technology (MIT)", faculty: "Engineering" },
      { name: "Kasturba Medical College", faculty: "Medicine" },
    ],
  },
  {
    seedKey: "seed-in-jadavpur",
    name: "Jadavpur University",
    shortName: "JU Kolkata",
    country: "India",
    countryCode: "IN",
    city: "Kolkata",
    state: "West Bengal",
    website: "https://jadavpuruniversity.in",
    domain: "jadavpuruniversity.in",
    timezone: "Asia/Kolkata",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Kolkata", isMain: true }],
    departments: [
      { name: "Faculty of Engineering & Technology", faculty: "Engineering" },
      { name: "Department of Computer Science and Engineering", faculty: "Computing" },
    ],
  },
  {
    seedKey: "seed-in-anna",
    name: "Anna University",
    shortName: "Anna Univ",
    country: "India",
    countryCode: "IN",
    city: "Chennai",
    state: "Tamil Nadu",
    website: "https://www.annauniv.edu",
    domain: "annauniv.edu",
    timezone: "Asia/Kolkata",
    isVerified: true,
    campuses: [{ name: "Guindy Main Campus", city: "Chennai", isMain: true }],
    departments: [
      { name: "College of Engineering, Guindy", faculty: "Engineering" },
      { name: "Department of Computer Science and Engineering", faculty: "Computing" },
    ],
  },

  // =========================================================================
  // BANGLADESH (BD)
  // =========================================================================
  {
    seedKey: "seed-bd-buet",
    name: "Bangladesh University of Engineering and Technology",
    shortName: "BUET",
    country: "Bangladesh",
    countryCode: "BD",
    city: "Dhaka",
    state: "Dhaka Division",
    website: "https://www.buet.ac.bd",
    domain: "buet.ac.bd",
    timezone: "Asia/Dhaka",
    isVerified: true,
    campuses: [{ name: "Main Campus (Palashi)", city: "Dhaka", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering (CSE)", faculty: "Electrical and Electronic Engineering" },
      { name: "Department of Electrical and Electronic Engineering (EEE)", faculty: "Engineering" },
      { name: "Department of Civil Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-bd-du",
    name: "University of Dhaka",
    shortName: "DU",
    country: "Bangladesh",
    countryCode: "BD",
    city: "Dhaka",
    state: "Dhaka Division",
    website: "https://www.du.ac.bd",
    domain: "du.ac.bd",
    timezone: "Asia/Dhaka",
    isVerified: true,
    campuses: [{ name: "Main Campus (Nilkhet)", city: "Dhaka", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "Engineering and Technology" },
      { name: "Faculty of Business Studies", faculty: "Business Studies" },
    ],
  },
  {
    seedKey: "seed-bd-nsu",
    name: "North South University",
    shortName: "NSU",
    country: "Bangladesh",
    countryCode: "BD",
    city: "Dhaka",
    state: "Dhaka Division",
    website: "https://www.northsouth.edu",
    domain: "northsouth.edu",
    timezone: "Asia/Dhaka",
    isVerified: true,
    campuses: [{ name: "Bashundhara Main Campus", city: "Dhaka", isMain: true }],
    departments: [
      { name: "Department of Electrical and Computer Engineering (ECE)", faculty: "School of Engineering and Physical Sciences" },
      { name: "School of Business and Economics (SBE)", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-bd-brac",
    name: "BRAC University",
    shortName: "BRACU",
    country: "Bangladesh",
    countryCode: "BD",
    city: "Dhaka",
    state: "Dhaka Division",
    website: "https://www.bracu.ac.bd",
    domain: "bracu.ac.bd",
    timezone: "Asia/Dhaka",
    isVerified: true,
    campuses: [{ name: "Merul Badda Main Campus", city: "Dhaka", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering (CSE)", faculty: "School of Data and Sciences" },
      { name: "BRAC Business School (BBS)", faculty: "Business" },
    ],
  },
  {
    seedKey: "seed-bd-cuet",
    name: "Chittagong University of Engineering & Technology",
    shortName: "CUET",
    country: "Bangladesh",
    countryCode: "BD",
    city: "Chittagong",
    state: "Chittagong Division",
    website: "https://www.cuet.ac.bd",
    domain: "cuet.ac.bd",
    timezone: "Asia/Dhaka",
    isVerified: true,
    campuses: [{ name: "Raozan Main Campus", city: "Chittagong", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "Electrical & Computer Engineering" },
      { name: "Department of Civil Engineering", faculty: "Engineering" },
    ],
  },
  {
    seedKey: "seed-bd-ruet",
    name: "Rajshahi University of Engineering & Technology",
    shortName: "RUET",
    country: "Bangladesh",
    countryCode: "BD",
    city: "Rajshahi",
    state: "Rajshahi Division",
    website: "https://www.ruet.ac.bd",
    domain: "ruet.ac.bd",
    timezone: "Asia/Dhaka",
    isVerified: true,
    campuses: [{ name: "Kazla Main Campus", city: "Rajshahi", isMain: true }],
    departments: [
      { name: "Faculty of Electrical and Computer Engineering", faculty: "Engineering" },
      { name: "Department of Computer Science & Engineering", faculty: "Computing" },
    ],
  },
  {
    seedKey: "seed-bd-sust",
    name: "Shahjalal University of Science and Technology",
    shortName: "SUST",
    country: "Bangladesh",
    countryCode: "BD",
    city: "Sylhet",
    state: "Sylhet Division",
    website: "https://www.sust.edu",
    domain: "sust.edu",
    timezone: "Asia/Dhaka",
    isVerified: true,
    campuses: [{ name: "Kumargaon Main Campus", city: "Sylhet", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "Applied Sciences & Technology" },
      { name: "Department of Software Engineering", faculty: "Applied Sciences & Technology" },
    ],
  },

  // =========================================================================
  // SRI LANKA (LK)
  // =========================================================================
  {
    seedKey: "seed-lk-colombo",
    name: "University of Colombo",
    shortName: "UoC",
    country: "Sri Lanka",
    countryCode: "LK",
    city: "Colombo",
    state: "Western Province",
    website: "https://cmb.ac.lk",
    domain: "cmb.ac.lk",
    timezone: "Asia/Colombo",
    isVerified: true,
    campuses: [{ name: "Cinnamon Gardens Main Campus", city: "Colombo", isMain: true }],
    departments: [
      { name: "University of Colombo School of Computing (UCSC)", faculty: "Computing" },
      { name: "Faculty of Science", faculty: "Science" },
      { name: "Faculty of Management and Finance", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-lk-moratuwa",
    name: "University of Moratuwa",
    shortName: "UoM",
    country: "Sri Lanka",
    countryCode: "LK",
    city: "Moratuwa",
    state: "Western Province",
    website: "https://uom.lk",
    domain: "uom.lk",
    timezone: "Asia/Colombo",
    isVerified: true,
    campuses: [{ name: "Katubedda Main Campus", city: "Moratuwa", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "Engineering" },
      { name: "Department of Electronic and Telecommunication Engineering", faculty: "Engineering" },
      { name: "Faculty of Information Technology", faculty: "Information Technology" },
    ],
  },
  {
    seedKey: "seed-lk-peradeniya",
    name: "University of Peradeniya",
    shortName: "UoP",
    country: "Sri Lanka",
    countryCode: "LK",
    city: "Peradeniya",
    state: "Central Province",
    website: "https://www.pdn.ac.lk",
    domain: "pdn.ac.lk",
    timezone: "Asia/Colombo",
    isVerified: true,
    campuses: [{ name: "Peradeniya Main Campus", city: "Kandy", isMain: true }],
    departments: [
      { name: "Department of Computer Engineering", faculty: "Faculty of Engineering" },
      { name: "Faculty of Science", faculty: "Science" },
    ],
  },
  {
    seedKey: "seed-lk-kelaniya",
    name: "University of Kelaniya",
    shortName: "UoK",
    country: "Sri Lanka",
    countryCode: "LK",
    city: "Kelaniya",
    state: "Western Province",
    website: "https://www.kln.ac.lk",
    domain: "kln.ac.lk",
    timezone: "Asia/Colombo",
    isVerified: true,
    campuses: [{ name: "Main Campus", city: "Kelaniya", isMain: true }],
    departments: [
      { name: "Faculty of Computing and Technology", faculty: "Computing" },
      { name: "Faculty of Commerce and Management Studies", faculty: "Commerce" },
    ],
  },

  // =========================================================================
  // NEPAL (NP)
  // =========================================================================
  {
    seedKey: "seed-np-tribhuvan",
    name: "Tribhuvan University",
    shortName: "TU",
    country: "Nepal",
    countryCode: "NP",
    city: "Kirtipur",
    state: "Bagmati Province",
    website: "https://tu.edu.np",
    domain: "tu.edu.np",
    timezone: "Asia/Kathmandu",
    isVerified: true,
    campuses: [
      { name: "Kirtipur Central Campus", city: "Kathmandu", isMain: true },
      { name: "Pulchowk Campus (IOE)", city: "Lalitpur", isMain: false },
    ],
    departments: [
      { name: "Institute of Engineering (IOE) - Department of Electronics and Computer Engineering", faculty: "Engineering" },
      { name: "Central Department of Computer Science and Information Technology", faculty: "Science & Technology" },
    ],
  },
  {
    seedKey: "seed-np-kathmandu",
    name: "Kathmandu University",
    shortName: "KU",
    country: "Nepal",
    countryCode: "NP",
    city: "Dhulikhel",
    state: "Bagmati Province",
    website: "https://ku.edu.np",
    domain: "ku.edu.np",
    timezone: "Asia/Kathmandu",
    isVerified: true,
    campuses: [{ name: "Dhulikhel Main Campus", city: "Dhulikhel", isMain: true }],
    departments: [
      { name: "Department of Computer Science and Engineering", faculty: "School of Engineering" },
      { name: "School of Management (KUSOM)", faculty: "Management" },
    ],
  },
  {
    seedKey: "seed-np-pokhara",
    name: "Pokhara University",
    shortName: "PU Nepal",
    country: "Nepal",
    countryCode: "NP",
    city: "Pokhara",
    state: "Gandaki Province",
    website: "https://pu.edu.np",
    domain: "pu.edu.np",
    timezone: "Asia/Kathmandu",
    isVerified: true,
    campuses: [{ name: "Lekhnath Main Campus", city: "Pokhara", isMain: true }],
    departments: [
      { name: "Faculty of Science and Technology", faculty: "Science and Technology" },
      { name: "Faculty of Management Studies", faculty: "Management" },
    ],
  },
];
